//! Autogenerated weights for `pallet_work`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-29.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.10GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_work`.
pub trait WeightInfo {
    /// Benchmarked weight of `submit_report`.
    fn submit_report(v: u32, e: u32) -> Weight;
    /// Benchmarked weight of `claim`.
    fn claim(n: u32) -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Gateways::Gateways` (r:1 w:0)
    /// Proof: `Gateways::Gateways` (`max_values`: None, `max_size`: Some(474), added: 2949, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Providers::Providers` (r:128 w:0)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:17 w:17)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Credits::Channels` (r:16 w:16)
    /// Proof: `Credits::Channels` (`max_values`: None, `max_size`: Some(190), added: 2665, mode: `MaxEncodedLen`)
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:17 w:17)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(247), added: 2722, mode: `MaxEncodedLen`)
    /// Storage: `Work::Params` (r:1 w:0)
    /// Proof: `Work::Params` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Emission::TotalBurned` (r:1 w:1)
    /// Proof: `Emission::TotalBurned` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Emission::EpochLength` (r:1 w:0)
    /// Proof: `Emission::EpochLength` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Work::HeldFor` (r:129 w:129)
    /// Proof: `Work::HeldFor` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
    /// Storage: `Work::WorkOf` (r:128 w:128)
    /// Proof: `Work::WorkOf` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
    /// Storage: `Work::Lifetime` (r:128 w:128)
    /// Proof: `Work::Lifetime` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    /// Storage: `Work::EpochWorks` (r:1 w:1)
    /// Proof: `Work::EpochWorks` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `Work::NextReportId` (r:1 w:1)
    /// Proof: `Work::NextReportId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Work::OldestReport` (r:1 w:0)
    /// Proof: `Work::OldestReport` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Work::Reports` (r:0 w:1)
    /// Proof: `Work::Reports` (`max_values`: None, `max_size`: Some(16662), added: 19137, mode: `MaxEncodedLen`)
    fn submit_report(v: u32, e: u32) -> Weight {
        Weight::from_parts(1_020_074_570, 3939)
            .saturating_add(Weight::from_parts(1_184_825_328, 0).saturating_mul(v.into()))
            .saturating_add(Weight::from_parts(22_722_320, 0).saturating_mul(e.into()))
            .saturating_add(T::DbWeight::get().reads(12_u64))
            .saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(v.into())))
            .saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(e.into())))
            .saturating_add(T::DbWeight::get().writes(7_u64))
            .saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(v.into())))
            .saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(e.into())))
            .saturating_add(Weight::from_parts(0, 5243).saturating_mul(e.into()))
            .saturating_add(Weight::from_parts(0, 2722).saturating_mul(v.into()))
    }
    /// Storage: `Work::EpochWorks` (r:64 w:0)
    /// Proof: `Work::EpochWorks` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `Work::WorkOf` (r:64 w:64)
    /// Proof: `Work::WorkOf` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:3 w:3)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Work::Unclaimed` (r:1 w:1)
    /// Proof: `Work::Unclaimed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Work::Lifetime` (r:1 w:1)
    /// Proof: `Work::Lifetime` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    /// Storage: `Work::HeldFor` (r:64 w:64)
    /// Proof: `Work::HeldFor` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(247), added: 2722, mode: `MaxEncodedLen`)
    fn claim(n: u32) -> Weight {
        Weight::from_parts(67_324_592, 8799)
            .saturating_add(Weight::from_parts(91_609_096, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(6_u64))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2619).saturating_mul(n.into()))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn submit_report(v: u32, e: u32) -> Weight {
        Weight::from_parts(1_020_074_570, 3939)
            .saturating_add(Weight::from_parts(1_184_825_328, 0).saturating_mul(v.into()))
            .saturating_add(Weight::from_parts(22_722_320, 0).saturating_mul(e.into()))
            .saturating_add(RocksDbWeight::get().reads(12_u64))
            .saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(v.into())))
            .saturating_add(RocksDbWeight::get().reads((4_u64).saturating_mul(e.into())))
            .saturating_add(RocksDbWeight::get().writes(7_u64))
            .saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(v.into())))
            .saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(e.into())))
            .saturating_add(Weight::from_parts(0, 5243).saturating_mul(e.into()))
            .saturating_add(Weight::from_parts(0, 2722).saturating_mul(v.into()))
    }
    fn claim(n: u32) -> Weight {
        Weight::from_parts(67_324_592, 8799)
            .saturating_add(Weight::from_parts(91_609_096, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(6_u64))
            .saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(6_u64))
            .saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2619).saturating_mul(n.into()))
    }
}
