//! Autogenerated weights for `pallet_poa_admin`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-27.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_poa_admin`.
pub trait WeightInfo {
    /// Benchmarked weight of `dispatch_as_root`.
    fn dispatch_as_root() -> Weight;
    /// Benchmarked weight of `set_threshold`.
    fn set_threshold() -> Weight;
    /// Benchmarked weight of `set_members`.
    fn set_members(m: u32) -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `PoaAdmin::Threshold` (r:1 w:0)
    /// Proof: `PoaAdmin::Threshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn dispatch_as_root() -> Weight {
        Weight::from_parts(11_702_000, 1489).saturating_add(T::DbWeight::get().reads(1_u64))
    }
    /// Storage: `PoaAdmin::Threshold` (r:1 w:1)
    /// Proof: `PoaAdmin::Threshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `PoaCouncil::Members` (r:1 w:0)
    /// Proof: `PoaCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn set_threshold() -> Weight {
        Weight::from_parts(14_789_000, 2123)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `PoaAdmin::Threshold` (r:1 w:1)
    /// Proof: `PoaAdmin::Threshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `PoaCouncil::Members` (r:1 w:1)
    /// Proof: `PoaCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `PoaCouncil::Proposals` (r:1 w:0)
    /// Proof: `PoaCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `PoaCouncil::Prime` (r:0 w:1)
    /// Proof: `PoaCouncil::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn set_members(m: u32) -> Weight {
        Weight::from_parts(17_494_695, 1642)
            .saturating_add(Weight::from_parts(72_152, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn dispatch_as_root() -> Weight {
        Weight::from_parts(11_702_000, 1489).saturating_add(RocksDbWeight::get().reads(1_u64))
    }
    fn set_threshold() -> Weight {
        Weight::from_parts(14_789_000, 2123)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn set_members(m: u32) -> Weight {
        Weight::from_parts(17_494_695, 1642)
            .saturating_add(Weight::from_parts(72_152, 0).saturating_mul(m.into()))
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
}
