//! Autogenerated weights for `pallet_providers`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-29.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_providers`.
pub trait WeightInfo {
    /// Benchmarked weight of `register`.
    fn register(m: u32) -> Weight;
    /// Benchmarked weight of `update`.
    fn update(m: u32) -> Weight;
    /// Benchmarked weight of `heartbeat`.
    fn heartbeat() -> Weight;
    /// Benchmarked weight of `bond_extra`.
    fn bond_extra() -> Weight;
    /// Benchmarked weight of `unbond`.
    fn unbond() -> Weight;
    /// Benchmarked weight of `exit`.
    fn exit(m: u32) -> Weight;
    /// Benchmarked weight of `withdraw_unbonded`.
    fn withdraw_unbonded() -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Providers::Providers` (r:1 w:1)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `ModelRegistry::Models` (r:16 w:0)
    /// Proof: `ModelRegistry::Models` (`max_values`: None, `max_size`: Some(33250), added: 35725, mode: `MaxEncodedLen`)
    /// Storage: `Providers::Params` (r:1 w:0)
    /// Proof: `Providers::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
    /// Storage: `Providers::ModelProviders` (r:0 w:16)
    /// Proof: `Providers::ModelProviders` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    fn register(m: u32) -> Weight {
        Weight::from_parts(69_168_411, 6233)
            .saturating_add(Weight::from_parts(3_610_587, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(m.into())))
            .saturating_add(T::DbWeight::get().writes(2_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(m.into())))
            .saturating_add(Weight::from_parts(0, 35725).saturating_mul(m.into()))
    }
    /// Storage: `Providers::Providers` (r:1 w:1)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `ModelRegistry::Models` (r:16 w:0)
    /// Proof: `ModelRegistry::Models` (`max_values`: None, `max_size`: Some(33250), added: 35725, mode: `MaxEncodedLen`)
    /// Storage: `Providers::ModelProviders` (r:0 w:32)
    /// Proof: `Providers::ModelProviders` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    fn update(m: u32) -> Weight {
        Weight::from_parts(50_893_304, 6233)
            .saturating_add(Weight::from_parts(3_591_216, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(m.into())))
            .saturating_add(T::DbWeight::get().writes(17_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(m.into())))
            .saturating_add(Weight::from_parts(0, 35725).saturating_mul(m.into()))
    }
    /// Storage: `Providers::Providers` (r:1 w:1)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `Providers::Params` (r:1 w:0)
    /// Proof: `Providers::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    fn heartbeat() -> Weight {
        Weight::from_parts(19_375_000, 6233)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Providers::Providers` (r:1 w:1)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
    fn bond_extra() -> Weight {
        Weight::from_parts(62_887_000, 6233)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Providers::Providers` (r:1 w:1)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `Providers::Params` (r:1 w:0)
    /// Proof: `Providers::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    fn unbond() -> Weight {
        Weight::from_parts(26_377_000, 6233)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Providers::Providers` (r:1 w:1)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `Providers::Params` (r:1 w:0)
    /// Proof: `Providers::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    /// Storage: `Providers::ModelProviders` (r:0 w:16)
    /// Proof: `Providers::ModelProviders` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    fn exit(m: u32) -> Weight {
        Weight::from_parts(23_936_203, 6233)
            .saturating_add(Weight::from_parts(1_502_294, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(m.into())))
    }
    /// Storage: `Providers::Providers` (r:1 w:1)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(53_693_000, 6233)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn register(m: u32) -> Weight {
        Weight::from_parts(69_168_411, 6233)
            .saturating_add(Weight::from_parts(3_610_587, 0).saturating_mul(m.into()))
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(m.into())))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(m.into())))
            .saturating_add(Weight::from_parts(0, 35725).saturating_mul(m.into()))
    }
    fn update(m: u32) -> Weight {
        Weight::from_parts(50_893_304, 6233)
            .saturating_add(Weight::from_parts(3_591_216, 0).saturating_mul(m.into()))
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(m.into())))
            .saturating_add(RocksDbWeight::get().writes(17_u64))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(m.into())))
            .saturating_add(Weight::from_parts(0, 35725).saturating_mul(m.into()))
    }
    fn heartbeat() -> Weight {
        Weight::from_parts(19_375_000, 6233)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn bond_extra() -> Weight {
        Weight::from_parts(62_887_000, 6233)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn unbond() -> Weight {
        Weight::from_parts(26_377_000, 6233)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn exit(m: u32) -> Weight {
        Weight::from_parts(23_936_203, 6233)
            .saturating_add(Weight::from_parts(1_502_294, 0).saturating_mul(m.into()))
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(m.into())))
    }
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(53_693_000, 6233)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
}
