[toolchain]
channel = "1.94.1"
# rust-src and wasm32v1-none are required by substrate-wasm-builder to build the runtime.
components = ["rustfmt", "clippy", "rust-src"]
targets = ["wasm32-unknown-unknown", "wasm32v1-none"]
profile = "minimal"
