//! Autogenerated weights for `pallet_ac_offences`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-26.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_ac_offences`.
pub trait WeightInfo {
    /// Benchmarked weight of `authorize_report_equivocation`.
    fn authorize_report_equivocation() -> Weight;
    /// Benchmarked weight of `report_equivocation`.
    fn report_equivocation() -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::CurrentSetId` (r:1 w:0)
    /// Proof: `ValidatorSet::CurrentSetId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::OldestSet` (r:1 w:0)
    /// Proof: `ValidatorSet::OldestSet` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::SetHistory` (r:1 w:0)
    /// Proof: `ValidatorSet::SetHistory` (`max_values`: None, `max_size`: Some(260126), added: 262601, mode: `MaxEncodedLen`)
    /// Storage: `AuraPq::CurrentSlot` (r:1 w:0)
    /// Proof: `AuraPq::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::Authorities` (r:1 w:0)
    /// Proof: `ValidatorSet::Authorities` (`max_values`: Some(1), `max_size`: Some(260102), added: 260597, mode: `MaxEncodedLen`)
    /// Storage: `Offences::Reports` (r:1 w:0)
    /// Proof: `Offences::Reports` (`max_values`: None, `max_size`: Some(2626), added: 5101, mode: `MaxEncodedLen`)
    /// Storage: `Offences::Offenders` (r:1 w:0)
    /// Proof: `Offences::Offenders` (`max_values`: None, `max_size`: Some(519518), added: 521993, mode: `MaxEncodedLen`)
    fn authorize_report_equivocation() -> Weight {
        Weight::from_parts(1_956_465_000, 522983).saturating_add(T::DbWeight::get().reads(8_u64))
    }
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::CurrentSetId` (r:1 w:0)
    /// Proof: `ValidatorSet::CurrentSetId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::OldestSet` (r:1 w:0)
    /// Proof: `ValidatorSet::OldestSet` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::SetHistory` (r:1 w:0)
    /// Proof: `ValidatorSet::SetHistory` (`max_values`: None, `max_size`: Some(260126), added: 262601, mode: `MaxEncodedLen`)
    /// Storage: `AuraPq::CurrentSlot` (r:1 w:0)
    /// Proof: `AuraPq::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::Authorities` (r:1 w:0)
    /// Proof: `ValidatorSet::Authorities` (`max_values`: Some(1), `max_size`: Some(260102), added: 260597, mode: `MaxEncodedLen`)
    /// Storage: `Offences::Reports` (r:1 w:1)
    /// Proof: `Offences::Reports` (`max_values`: None, `max_size`: Some(2626), added: 5101, mode: `MaxEncodedLen`)
    /// Storage: `Offences::Offenders` (r:1 w:1)
    /// Proof: `Offences::Offenders` (`max_values`: None, `max_size`: Some(519518), added: 521993, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::PendingRemovals` (r:1 w:1)
    /// Proof: `ValidatorSet::PendingRemovals` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    fn report_equivocation() -> Weight {
        Weight::from_parts(2_013_792_000, 522983)
            .saturating_add(T::DbWeight::get().reads(9_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn authorize_report_equivocation() -> Weight {
        Weight::from_parts(1_956_465_000, 522983).saturating_add(RocksDbWeight::get().reads(8_u64))
    }
    fn report_equivocation() -> Weight {
        Weight::from_parts(2_013_792_000, 522983)
            .saturating_add(RocksDbWeight::get().reads(9_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
}
