//! chain/pq-transaction-auth Requirement "授权成本计入权重" / Scenario "权重来自基准", and
//! chain/pq-accounts Requirement "轮换操作计量" / Scenario "最坏情况权重" (task 4.4).
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use ac_runtime::Runtime;
use frame_support::weights::Weight;
use pallet_pq_accounts::weights::{SubstrateWeight, WeightInfo};

type Configured = <Runtime as pallet_pq_accounts::Config>::WeightInfo;

fn generated() -> [Weight; 5] {
    [
        SubstrateWeight::<Runtime>::rotate_key(),
        SubstrateWeight::<Runtime>::authorize_ml_dsa_44(),
        SubstrateWeight::<Runtime>::authorize_ml_dsa_65(),
        SubstrateWeight::<Runtime>::authorize_ml_dsa_87(),
        SubstrateWeight::<Runtime>::register_key(),
    ]
}

fn configured() -> [Weight; 5] {
    [
        Configured::rotate_key(),
        Configured::authorize_ml_dsa_44(),
        Configured::authorize_ml_dsa_65(),
        Configured::authorize_ml_dsa_87(),
        Configured::register_key(),
    ]
}

#[test]
fn runtime_uses_benchmarked_weights() {
    assert_eq!(configured(), generated());
    assert!(generated().iter().all(|w| w.ref_time() > 0));
    // The generated file is marked as benchmark output.
    let source = include_str!("../../pallets/pq-accounts/src/weights.rs");
    assert!(source.starts_with("//! Autogenerated weights for `pallet_pq_accounts`."));
}

#[test]
fn authorization_cost_grows_with_parameter_set() {
    let [_, a44, a65, a87, _] = configured();
    assert!(a44.ref_time() < a65.ref_time() && a65.ref_time() < a87.ref_time());
}

#[test]
fn rotation_covers_the_largest_proof_of_possession() {
    let [rotate, _, _, a87, _] = configured();
    assert!(rotate.ref_time() >= a87.ref_time());
}

// m2-finality 6.4: the three consensus pallets use their benchmarked weights, and the report
// of double signing costs at least two ML-DSA-65 verifications.
#[test]
fn consensus_pallets_use_benchmarked_weights() {
    use pallet_ac_offences::weights::WeightInfo as _;
    use pallet_randomness_cr::weights::WeightInfo as _;
    use pallet_validator_set::weights::WeightInfo as _;
    type Vs = <Runtime as pallet_validator_set::Config>::WeightInfo;
    type Of = <Runtime as pallet_ac_offences::Config>::WeightInfo;
    type Rc = <Runtime as pallet_randomness_cr::Config>::WeightInfo;
    let pairs = [
        (
            Vs::epoch_boundary_with_change(100),
            pallet_validator_set::weights::SubstrateWeight::<Runtime>::epoch_boundary_with_change(100),
        ),
        (
            Vs::epoch_boundary_without_change(100),
            pallet_validator_set::weights::SubstrateWeight::<Runtime>::epoch_boundary_without_change(100),
        ),
        (
            Of::authorize_report_equivocation(),
            pallet_ac_offences::weights::SubstrateWeight::<Runtime>::authorize_report_equivocation(),
        ),
        (
            Of::report_equivocation(),
            pallet_ac_offences::weights::SubstrateWeight::<Runtime>::report_equivocation(),
        ),
        (
            Rc::note_randomness(),
            pallet_randomness_cr::weights::SubstrateWeight::<Runtime>::note_randomness(),
        ),
        (
            Rc::conclude_epoch(100),
            pallet_randomness_cr::weights::SubstrateWeight::<Runtime>::conclude_epoch(100),
        ),
    ];
    for (configured, generated) in pairs {
        assert_eq!(configured, generated);
        assert!(generated.ref_time() > 0);
    }
    for (source, pallet) in [
        (
            include_str!("../../pallets/validator-set/src/weights.rs"),
            "pallet_validator_set",
        ),
        (
            include_str!("../../pallets/offences/src/weights.rs"),
            "pallet_ac_offences",
        ),
        (
            include_str!("../../pallets/randomness-cr/src/weights.rs"),
            "pallet_randomness_cr",
        ),
    ] {
        assert!(source.starts_with(&format!("//! Autogenerated weights for `{pallet}`.")));
    }
    // Authorizing a report verifies two ML-DSA-65 signatures: more than one authorization.
    let one_verification = SubstrateWeight::<Runtime>::authorize_ml_dsa_65();
    assert!(Of::authorize_report_equivocation().ref_time() > one_verification.ref_time());
}
