//! chain/pq-transaction-auth Requirement "授权成本计入权重" / Scenario "权重来自基准", and
//! chain/pq-accounts Requirement "轮换操作计量" / Scenario "最坏情况权重" (task 4.4).
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use ac_runtime::Runtime;
use frame_support::weights::Weight;
use pallet_pq_accounts::weights::{SubstrateWeight, WeightInfo};

type Configured = <Runtime as pallet_pq_accounts::Config>::WeightInfo;

fn generated() -> [Weight; 5] {
    [
        SubstrateWeight::<Runtime>::rotate_key(),
        SubstrateWeight::<Runtime>::authorize_ml_dsa_44(),
        SubstrateWeight::<Runtime>::authorize_ml_dsa_65(),
        SubstrateWeight::<Runtime>::authorize_ml_dsa_87(),
        SubstrateWeight::<Runtime>::register_key(),
    ]
}

fn configured() -> [Weight; 5] {
    [
        Configured::rotate_key(),
        Configured::authorize_ml_dsa_44(),
        Configured::authorize_ml_dsa_65(),
        Configured::authorize_ml_dsa_87(),
        Configured::register_key(),
    ]
}

#[test]
fn runtime_uses_benchmarked_weights() {
    assert_eq!(configured(), generated());
    assert!(generated().iter().all(|w| w.ref_time() > 0));
    // The generated file is marked as benchmark output.
    let source = include_str!("../../pallets/pq-accounts/src/weights.rs");
    assert!(source.starts_with("//! Autogenerated weights for `pallet_pq_accounts`."));
}

#[test]
fn authorization_cost_grows_with_parameter_set() {
    let [_, a44, a65, a87, _] = configured();
    assert!(a44.ref_time() < a65.ref_time() && a65.ref_time() < a87.ref_time());
}

#[test]
fn rotation_covers_the_largest_proof_of_possession() {
    let [rotate, _, _, a87, _] = configured();
    assert!(rotate.ref_time() >= a87.ref_time());
}
