//! Autogenerated weights for `pallet_ref_rate`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-29.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_ref_rate`.
pub trait WeightInfo {
    /// Benchmarked weight of `set_rate`.
    fn set_rate() -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `PoaAdmin::Threshold` (r:1 w:0)
    /// Proof: `PoaAdmin::Threshold` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:1)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Params` (r:1 w:0)
    /// Proof: `RefRate::Params` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn set_rate() -> Weight {
        Weight::from_parts(17_531_000, 1505)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn set_rate() -> Weight {
        Weight::from_parts(17_531_000, 1505)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
