//! Autogenerated weights for `pallet_treasury_dual`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-27.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.10GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_treasury_dual`.
pub trait WeightInfo {
    /// Benchmarked weight of `spend`.
    fn spend() -> Weight;
    /// Benchmarked weight of `spend_floor`.
    fn spend_floor() -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn spend() -> Weight {
        Weight::from_parts(52_367_000, 6196)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `TreasuryDual::FloorBatches` (r:1 w:0)
    /// Proof: `TreasuryDual::FloorBatches` (`max_values`: Some(1), `max_size`: Some(625), added: 1120, mode: `MaxEncodedLen`)
    /// Storage: `TreasuryDual::FloorMatured` (r:1 w:0)
    /// Proof: `TreasuryDual::FloorMatured` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `TreasuryDual::FloorSpent` (r:1 w:1)
    /// Proof: `TreasuryDual::FloorSpent` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn spend_floor() -> Weight {
        Weight::from_parts(62_604_000, 6196)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn spend() -> Weight {
        Weight::from_parts(52_367_000, 6196)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn spend_floor() -> Weight {
        Weight::from_parts(62_604_000, 6196)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
}
