//! Autogenerated weights for `pallet_gateways`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-29.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_gateways`.
pub trait WeightInfo {
    /// Benchmarked weight of `register`.
    fn register() -> Weight;
    /// Benchmarked weight of `update`.
    fn update() -> Weight;
    /// Benchmarked weight of `bond_extra`.
    fn bond_extra() -> Weight;
    /// Benchmarked weight of `unbond`.
    fn unbond() -> Weight;
    /// Benchmarked weight of `exit`.
    fn exit() -> Weight;
    /// Benchmarked weight of `withdraw_unbonded`.
    fn withdraw_unbonded() -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Gateways::Gateways` (r:1 w:1)
    /// Proof: `Gateways::Gateways` (`max_values`: None, `max_size`: Some(474), added: 2949, mode: `MaxEncodedLen`)
    /// Storage: `Gateways::Params` (r:1 w:0)
    /// Proof: `Gateways::Params` (`max_values`: Some(1), `max_size`: Some(26), added: 521, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
    fn register() -> Weight {
        Weight::from_parts(64_885_000, 3939)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Gateways::Gateways` (r:1 w:1)
    /// Proof: `Gateways::Gateways` (`max_values`: None, `max_size`: Some(474), added: 2949, mode: `MaxEncodedLen`)
    /// Storage: `Gateways::Params` (r:1 w:0)
    /// Proof: `Gateways::Params` (`max_values`: Some(1), `max_size`: Some(26), added: 521, mode: `MaxEncodedLen`)
    fn update() -> Weight {
        Weight::from_parts(18_249_000, 3939)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Gateways::Gateways` (r:1 w:1)
    /// Proof: `Gateways::Gateways` (`max_values`: None, `max_size`: Some(474), added: 2949, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
    fn bond_extra() -> Weight {
        Weight::from_parts(60_481_000, 3939)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Gateways::Gateways` (r:1 w:1)
    /// Proof: `Gateways::Gateways` (`max_values`: None, `max_size`: Some(474), added: 2949, mode: `MaxEncodedLen`)
    /// Storage: `Gateways::Params` (r:1 w:0)
    /// Proof: `Gateways::Params` (`max_values`: Some(1), `max_size`: Some(26), added: 521, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    fn unbond() -> Weight {
        Weight::from_parts(24_553_000, 3939)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Gateways::Gateways` (r:1 w:1)
    /// Proof: `Gateways::Gateways` (`max_values`: None, `max_size`: Some(474), added: 2949, mode: `MaxEncodedLen`)
    /// Storage: `Gateways::Params` (r:1 w:0)
    /// Proof: `Gateways::Params` (`max_values`: Some(1), `max_size`: Some(26), added: 521, mode: `MaxEncodedLen`)
    fn exit() -> Weight {
        Weight::from_parts(20_487_000, 3939)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Gateways::Gateways` (r:1 w:1)
    /// Proof: `Gateways::Gateways` (`max_values`: None, `max_size`: Some(474), added: 2949, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(52_516_000, 3939)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn register() -> Weight {
        Weight::from_parts(64_885_000, 3939)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn update() -> Weight {
        Weight::from_parts(18_249_000, 3939)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn bond_extra() -> Weight {
        Weight::from_parts(60_481_000, 3939)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn unbond() -> Weight {
        Weight::from_parts(24_553_000, 3939)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn exit() -> Weight {
        Weight::from_parts(20_487_000, 3939)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(52_516_000, 3939)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
}
