//! Autogenerated weights for `pallet_audit`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-10-01.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_audit`.
pub trait WeightInfo {
    /// Benchmarked weight of `register`.
    fn register() -> Weight;
    /// Benchmarked weight of `bond_extra`.
    fn bond_extra() -> Weight;
    /// Benchmarked weight of `unbond`.
    fn unbond() -> Weight;
    /// Benchmarked weight of `exit`.
    fn exit() -> Weight;
    /// Benchmarked weight of `withdraw_unbonded`.
    fn withdraw_unbonded() -> Weight;
    /// Benchmarked weight of `submit_verdict`.
    fn submit_verdict() -> Weight;
    /// Benchmarked weight of `vote`.
    fn vote() -> Weight;
    /// Benchmarked weight of `close_dispute`.
    fn close_dispute() -> Weight;
    /// Benchmarked weight of `set_params`.
    fn set_params() -> Weight;
    /// Benchmarked weight of `start_round`.
    fn start_round(n: u32) -> Weight;
    /// Benchmarked weight of `prune`.
    fn prune(n: u32) -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Audit::Auditors` (r:1 w:1)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Providers::Providers` (r:1 w:0)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `Gateways::Gateways` (r:1 w:0)
    /// Proof: `Gateways::Gateways` (`max_values`: None, `max_size`: Some(474), added: 2949, mode: `MaxEncodedLen`)
    /// Storage: `Audit::AuditorCount` (r:1 w:1)
    /// Proof: `Audit::AuditorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(265), added: 2740, mode: `MaxEncodedLen`)
    fn register() -> Weight {
        Weight::from_parts(104_312_000, 6233)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `Audit::Auditors` (r:1 w:1)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(265), added: 2740, mode: `MaxEncodedLen`)
    fn bond_extra() -> Weight {
        Weight::from_parts(82_748_000, 3730)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `Audit::Auditors` (r:1 w:1)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Params` (r:1 w:0)
    /// Proof: `Audit::Params` (`max_values`: Some(1), `max_size`: Some(23), added: 518, mode: `MaxEncodedLen`)
    fn unbond() -> Weight {
        Weight::from_parts(35_999_000, 3675)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Audit::Auditors` (r:1 w:1)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Params` (r:1 w:0)
    /// Proof: `Audit::Params` (`max_values`: Some(1), `max_size`: Some(23), added: 518, mode: `MaxEncodedLen`)
    fn exit() -> Weight {
        Weight::from_parts(31_833_000, 3675)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Audit::Auditors` (r:1 w:1)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(265), added: 2740, mode: `MaxEncodedLen`)
    /// Storage: `Audit::AuditorCount` (r:1 w:1)
    /// Proof: `Audit::AuditorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(78_519_000, 3730)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `Audit::Params` (r:1 w:0)
    /// Proof: `Audit::Params` (`max_values`: Some(1), `max_size`: Some(23), added: 518, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Seeds` (r:1 w:0)
    /// Proof: `Audit::Seeds` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Rosters` (r:1 w:0)
    /// Proof: `Audit::Rosters` (`max_values`: None, `max_size`: Some(32014), added: 34489, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Verdicts` (r:2 w:1)
    /// Proof: `Audit::Verdicts` (`max_values`: None, `max_size`: Some(1405), added: 3880, mode: `MaxEncodedLen`)
    /// Storage: `PqAccounts::Keys` (r:2 w:0)
    /// Proof: `PqAccounts::Keys` (`max_values`: None, `max_size`: Some(2629), added: 5104, mode: `MaxEncodedLen`)
    /// Storage: `Providers::Providers` (r:1 w:0)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::UsedRequests` (r:1 w:1)
    /// Proof: `Audit::UsedRequests` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RoundVerdicts` (r:1 w:1)
    /// Proof: `Audit::RoundVerdicts` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    /// Storage: `Audit::ProviderStats` (r:1 w:1)
    /// Proof: `Audit::ProviderStats` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Activity` (r:1 w:1)
    /// Proof: `Audit::Activity` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Audit::OpenDispute` (r:1 w:1)
    /// Proof: `Audit::OpenDispute` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Audit::NextDispute` (r:1 w:1)
    /// Proof: `Audit::NextDispute` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RoundRequests` (r:0 w:1)
    /// Proof: `Audit::RoundRequests` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Disputes` (r:0 w:1)
    /// Proof: `Audit::Disputes` (`max_values`: None, `max_size`: Some(1151), added: 3626, mode: `MaxEncodedLen`)
    fn submit_verdict() -> Weight {
        Weight::from_parts(3_608_531_000, 35479)
            .saturating_add(T::DbWeight::get().reads(19_u64))
            .saturating_add(T::DbWeight::get().writes(11_u64))
    }
    /// Storage: `Audit::Params` (r:1 w:0)
    /// Proof: `Audit::Params` (`max_values`: Some(1), `max_size`: Some(23), added: 518, mode: `MaxEncodedLen`)
    /// Storage: `Audit::OpenDispute` (r:1 w:1)
    /// Proof: `Audit::OpenDispute` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Disputes` (r:1 w:1)
    /// Proof: `Audit::Disputes` (`max_values`: None, `max_size`: Some(1151), added: 3626, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Activity` (r:2 w:2)
    /// Proof: `Audit::Activity` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:5 w:5)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Auditors` (r:2 w:2)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:2 w:2)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(265), added: 2740, mode: `MaxEncodedLen`)
    /// Storage: `Emission::TotalBurned` (r:1 w:1)
    /// Proof: `Emission::TotalBurned` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn vote() -> Weight {
        Weight::from_parts(428_952_000, 14005)
            .saturating_add(T::DbWeight::get().reads(17_u64))
            .saturating_add(T::DbWeight::get().writes(14_u64))
    }
    /// Storage: `Audit::Params` (r:1 w:0)
    /// Proof: `Audit::Params` (`max_values`: Some(1), `max_size`: Some(23), added: 518, mode: `MaxEncodedLen`)
    /// Storage: `Audit::OpenDispute` (r:1 w:1)
    /// Proof: `Audit::OpenDispute` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Disputes` (r:1 w:1)
    /// Proof: `Audit::Disputes` (`max_values`: None, `max_size`: Some(1151), added: 3626, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Activity` (r:3 w:3)
    /// Proof: `Audit::Activity` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    fn close_dispute() -> Weight {
        Weight::from_parts(102_683_000, 8547)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `Audit::Adjustable` (r:1 w:1)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    fn set_params() -> Weight {
        Weight::from_parts(28_131_000, 1519)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Auditors` (r:1001 w:0)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `RandomnessCr::Latest` (r:1 w:0)
    /// Proof: `RandomnessCr::Latest` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Seeds` (r:0 w:1)
    /// Proof: `Audit::Seeds` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Rosters` (r:0 w:1)
    /// Proof: `Audit::Rosters` (`max_values`: None, `max_size`: Some(32014), added: 34489, mode: `MaxEncodedLen`)
    /// Storage: `Audit::LastRound` (r:0 w:1)
    /// Proof: `Audit::LastRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn start_round(n: u32) -> Weight {
        Weight::from_parts(47_202_000, 3675)
            .saturating_add(Weight::from_parts(6_150_561, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(3_u64))
            .saturating_add(Weight::from_parts(0, 2685).saturating_mul(n.into()))
    }
    /// Storage: `Audit::PruneNext` (r:1 w:0)
    /// Proof: `Audit::PruneNext` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RoundRequests` (r:200 w:200)
    /// Proof: `Audit::RoundRequests` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::UsedRequests` (r:0 w:200)
    /// Proof: `Audit::UsedRequests` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
    fn prune(n: u32) -> Weight {
        Weight::from_parts(11_439_315, 3606)
            .saturating_add(Weight::from_parts(4_250_598, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2518).saturating_mul(n.into()))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn register() -> Weight {
        Weight::from_parts(104_312_000, 6233)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn bond_extra() -> Weight {
        Weight::from_parts(82_748_000, 3730)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn unbond() -> Weight {
        Weight::from_parts(35_999_000, 3675)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn exit() -> Weight {
        Weight::from_parts(31_833_000, 3675)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(78_519_000, 3730)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
    fn submit_verdict() -> Weight {
        Weight::from_parts(3_608_531_000, 35479)
            .saturating_add(RocksDbWeight::get().reads(19_u64))
            .saturating_add(RocksDbWeight::get().writes(11_u64))
    }
    fn vote() -> Weight {
        Weight::from_parts(428_952_000, 14005)
            .saturating_add(RocksDbWeight::get().reads(17_u64))
            .saturating_add(RocksDbWeight::get().writes(14_u64))
    }
    fn close_dispute() -> Weight {
        Weight::from_parts(102_683_000, 8547)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(5_u64))
    }
    fn set_params() -> Weight {
        Weight::from_parts(28_131_000, 1519)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn start_round(n: u32) -> Weight {
        Weight::from_parts(47_202_000, 3675)
            .saturating_add(Weight::from_parts(6_150_561, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
            .saturating_add(Weight::from_parts(0, 2685).saturating_mul(n.into()))
    }
    fn prune(n: u32) -> Weight {
        Weight::from_parts(11_439_315, 3606)
            .saturating_add(Weight::from_parts(4_250_598, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2518).saturating_mul(n.into()))
    }
}
