//! Autogenerated weights for `pallet_audit`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-10-09.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.10GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_audit`.
pub trait WeightInfo {
    /// Benchmarked weight of `register`.
    fn register() -> Weight;
    /// Benchmarked weight of `bond_extra`.
    fn bond_extra() -> Weight;
    /// Benchmarked weight of `unbond`.
    fn unbond() -> Weight;
    /// Benchmarked weight of `exit`.
    fn exit() -> Weight;
    /// Benchmarked weight of `withdraw_unbonded`.
    fn withdraw_unbonded() -> Weight;
    /// Benchmarked weight of `submit_verdict`.
    fn submit_verdict() -> Weight;
    /// Benchmarked weight of `vote`.
    fn vote() -> Weight;
    /// Benchmarked weight of `close_dispute`.
    fn close_dispute() -> Weight;
    /// Benchmarked weight of `set_stats_config`.
    fn set_stats_config() -> Weight;
    /// Benchmarked weight of `clear_stale`.
    fn clear_stale(n: u32) -> Weight;
    /// Benchmarked weight of `set_params`.
    fn set_params() -> Weight;
    /// Benchmarked weight of `set_endpoint`.
    fn set_endpoint() -> Weight;
    /// Benchmarked weight of `start_round`.
    fn start_round(n: u32) -> Weight;
    /// Benchmarked weight of `prune`.
    fn prune(n: u32) -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Audit::Auditors` (r:1 w:1)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Providers::Providers` (r:1 w:0)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `Gateways::Gateways` (r:1 w:0)
    /// Proof: `Gateways::Gateways` (`max_values`: None, `max_size`: Some(474), added: 2949, mode: `MaxEncodedLen`)
    /// Storage: `Audit::AuditorCount` (r:1 w:1)
    /// Proof: `Audit::AuditorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
    fn register() -> Weight {
        Weight::from_parts(93_471_000, 6233)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `Audit::Auditors` (r:1 w:1)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
    fn bond_extra() -> Weight {
        Weight::from_parts(73_477_000, 3748)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `Audit::Auditors` (r:1 w:1)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Params` (r:1 w:0)
    /// Proof: `Audit::Params` (`max_values`: Some(1), `max_size`: Some(23), added: 518, mode: `MaxEncodedLen`)
    fn unbond() -> Weight {
        Weight::from_parts(34_778_000, 3675)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Audit::Auditors` (r:1 w:1)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Params` (r:1 w:0)
    /// Proof: `Audit::Params` (`max_values`: Some(1), `max_size`: Some(23), added: 518, mode: `MaxEncodedLen`)
    fn exit() -> Weight {
        Weight::from_parts(33_931_000, 3675)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Audit::Auditors` (r:1 w:1)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
    /// Storage: `Audit::AuditorCount` (r:1 w:1)
    /// Proof: `Audit::AuditorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Audit::AuditorEndpoints` (r:0 w:1)
    /// Proof: `Audit::AuditorEndpoints` (`max_values`: None, `max_size`: Some(1507), added: 3982, mode: `MaxEncodedLen`)
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(74_999_000, 3748)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `Audit::Params` (r:1 w:0)
    /// Proof: `Audit::Params` (`max_values`: Some(1), `max_size`: Some(23), added: 518, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Seeds` (r:1 w:0)
    /// Proof: `Audit::Seeds` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Rosters` (r:1 w:0)
    /// Proof: `Audit::Rosters` (`max_values`: None, `max_size`: Some(32014), added: 34489, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Verdicts` (r:128 w:1)
    /// Proof: `Audit::Verdicts` (`max_values`: None, `max_size`: Some(1509), added: 3984, mode: `MaxEncodedLen`)
    /// Storage: `Audit::StatsSettings` (r:1 w:0)
    /// Proof: `Audit::StatsSettings` (`max_values`: Some(1), `max_size`: Some(3), added: 498, mode: `MaxEncodedLen`)
    /// Storage: `PqAccounts::Keys` (r:2 w:0)
    /// Proof: `PqAccounts::Keys` (`max_values`: None, `max_size`: Some(2629), added: 5104, mode: `MaxEncodedLen`)
    /// Storage: `Providers::Providers` (r:1 w:0)
    /// Proof: `Providers::Providers` (`max_values`: None, `max_size`: Some(2768), added: 5243, mode: `MaxEncodedLen`)
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::UsedRequests` (r:1 w:1)
    /// Proof: `Audit::UsedRequests` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RoundVerdicts` (r:1 w:1)
    /// Proof: `Audit::RoundVerdicts` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    /// Storage: `Audit::ProviderStats` (r:1 w:1)
    /// Proof: `Audit::ProviderStats` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Activity` (r:1 w:1)
    /// Proof: `Audit::Activity` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Audit::OpenDispute` (r:1 w:1)
    /// Proof: `Audit::OpenDispute` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Audit::SprtStates` (r:1 w:1)
    /// Proof: `Audit::SprtStates` (`max_values`: None, `max_size`: Some(5164), added: 7639, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RetainedVerdicts` (r:128 w:1)
    /// Proof: `Audit::RetainedVerdicts` (`max_values`: None, `max_size`: Some(1509), added: 3984, mode: `MaxEncodedLen`)
    /// Storage: `Audit::NextDispute` (r:1 w:1)
    /// Proof: `Audit::NextDispute` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RoundRequests` (r:0 w:1)
    /// Proof: `Audit::RoundRequests` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Disputes` (r:0 w:1)
    /// Proof: `Audit::Disputes` (`max_values`: None, `max_size`: Some(5187), added: 7662, mode: `MaxEncodedLen`)
    fn submit_verdict() -> Weight {
        Weight::from_parts(5_574_556_000, 510942)
            .saturating_add(T::DbWeight::get().reads(275_u64))
            .saturating_add(T::DbWeight::get().writes(13_u64))
    }
    /// Storage: `Audit::Params` (r:1 w:0)
    /// Proof: `Audit::Params` (`max_values`: Some(1), `max_size`: Some(23), added: 518, mode: `MaxEncodedLen`)
    /// Storage: `Audit::OpenDispute` (r:1 w:1)
    /// Proof: `Audit::OpenDispute` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Disputes` (r:1 w:1)
    /// Proof: `Audit::Disputes` (`max_values`: None, `max_size`: Some(5187), added: 7662, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Activity` (r:2 w:2)
    /// Proof: `Audit::Activity` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:5 w:5)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Auditors` (r:2 w:2)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:2 w:2)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
    /// Storage: `Emission::TotalBurned` (r:1 w:1)
    /// Proof: `Emission::TotalBurned` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RetainedVerdicts` (r:1 w:0)
    /// Proof: `Audit::RetainedVerdicts` (`max_values`: None, `max_size`: Some(1509), added: 3984, mode: `MaxEncodedLen`)
    fn vote() -> Weight {
        Weight::from_parts(381_801_000, 14005)
            .saturating_add(T::DbWeight::get().reads(18_u64))
            .saturating_add(T::DbWeight::get().writes(14_u64))
    }
    /// Storage: `Audit::Params` (r:1 w:0)
    /// Proof: `Audit::Params` (`max_values`: Some(1), `max_size`: Some(23), added: 518, mode: `MaxEncodedLen`)
    /// Storage: `Audit::OpenDispute` (r:1 w:1)
    /// Proof: `Audit::OpenDispute` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Disputes` (r:1 w:1)
    /// Proof: `Audit::Disputes` (`max_values`: None, `max_size`: Some(5187), added: 7662, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Activity` (r:3 w:3)
    /// Proof: `Audit::Activity` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RetainedVerdicts` (r:1 w:0)
    /// Proof: `Audit::RetainedVerdicts` (`max_values`: None, `max_size`: Some(1509), added: 3984, mode: `MaxEncodedLen`)
    fn close_dispute() -> Weight {
        Weight::from_parts(95_449_000, 8652)
            .saturating_add(T::DbWeight::get().reads(8_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `Audit::StatsSettings` (r:1 w:1)
    /// Proof: `Audit::StatsSettings` (`max_values`: Some(1), `max_size`: Some(3), added: 498, mode: `MaxEncodedLen`)
    fn set_stats_config() -> Weight {
        Weight::from_parts(19_795_000, 1488)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Audit::StaleClearing` (r:1 w:1)
    /// Proof: `Audit::StaleClearing` (`max_values`: Some(1), `max_size`: Some(130), added: 625, mode: `MaxEncodedLen`)
    /// Storage: `Audit::StatsSettings` (r:1 w:0)
    /// Proof: `Audit::StatsSettings` (`max_values`: Some(1), `max_size`: Some(3), added: 498, mode: `MaxEncodedLen`)
    /// Storage: `Audit::SprtStates` (r:3 w:2)
    /// Proof: `Audit::SprtStates` (`max_values`: None, `max_size`: Some(5164), added: 7639, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RetainedVerdicts` (r:256 w:256)
    /// Proof: `Audit::RetainedVerdicts` (`max_values`: None, `max_size`: Some(1509), added: 3984, mode: `MaxEncodedLen`)
    /// Storage: `Audit::OpenDispute` (r:2 w:0)
    /// Proof: `Audit::OpenDispute` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    fn clear_stale(n: u32) -> Weight {
        Weight::from_parts(220_636_946, 8629)
            .saturating_add(Weight::from_parts(1_077_046_326, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().reads((130_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes((129_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 509952).saturating_mul(n.into()))
    }
    /// Storage: `Audit::Adjustable` (r:1 w:1)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    fn set_params() -> Weight {
        Weight::from_parts(20_186_000, 1519)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Audit::Auditors` (r:1 w:0)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Audit::AuditorEndpoints` (r:0 w:1)
    /// Proof: `Audit::AuditorEndpoints` (`max_values`: None, `max_size`: Some(1507), added: 3982, mode: `MaxEncodedLen`)
    fn set_endpoint() -> Weight {
        Weight::from_parts(24_888_000, 3675)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Audit::Adjustable` (r:1 w:0)
    /// Proof: `Audit::Adjustable` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Auditors` (r:1001 w:0)
    /// Proof: `Audit::Auditors` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `RandomnessCr::Latest` (r:1 w:0)
    /// Proof: `RandomnessCr::Latest` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Seeds` (r:0 w:1)
    /// Proof: `Audit::Seeds` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Rosters` (r:0 w:1)
    /// Proof: `Audit::Rosters` (`max_values`: None, `max_size`: Some(32014), added: 34489, mode: `MaxEncodedLen`)
    /// Storage: `Audit::LastRound` (r:0 w:1)
    /// Proof: `Audit::LastRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn start_round(n: u32) -> Weight {
        Weight::from_parts(41_532_601, 3675)
            .saturating_add(Weight::from_parts(5_328_700, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(3_u64))
            .saturating_add(Weight::from_parts(0, 2685).saturating_mul(n.into()))
    }
    /// Storage: `Audit::PruneNext` (r:1 w:1)
    /// Proof: `Audit::PruneNext` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RoundRequests` (r:1 w:0)
    /// Proof: `Audit::RoundRequests` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `Audit::Verdicts` (r:201 w:200)
    /// Proof: `Audit::Verdicts` (`max_values`: None, `max_size`: Some(1509), added: 3984, mode: `MaxEncodedLen`)
    /// Storage: `Audit::StatsSettings` (r:1 w:0)
    /// Proof: `Audit::StatsSettings` (`max_values`: Some(1), `max_size`: Some(3), added: 498, mode: `MaxEncodedLen`)
    /// Storage: `Audit::SprtStates` (r:200 w:0)
    /// Proof: `Audit::SprtStates` (`max_values`: None, `max_size`: Some(5164), added: 7639, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RoundVerdicts` (r:0 w:1)
    /// Proof: `Audit::RoundVerdicts` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    /// Storage: `Audit::RetainedVerdicts` (r:0 w:200)
    /// Proof: `Audit::RetainedVerdicts` (`max_values`: None, `max_size`: Some(1509), added: 3984, mode: `MaxEncodedLen`)
    fn prune(n: u32) -> Weight {
        Weight::from_parts(54_527_000, 4974)
            .saturating_add(Weight::from_parts(19_802_279, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(2_u64))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 7639).saturating_mul(n.into()))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn register() -> Weight {
        Weight::from_parts(93_471_000, 6233)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn bond_extra() -> Weight {
        Weight::from_parts(73_477_000, 3748)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn unbond() -> Weight {
        Weight::from_parts(34_778_000, 3675)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn exit() -> Weight {
        Weight::from_parts(33_931_000, 3675)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(74_999_000, 3748)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(5_u64))
    }
    fn submit_verdict() -> Weight {
        Weight::from_parts(5_574_556_000, 510942)
            .saturating_add(RocksDbWeight::get().reads(275_u64))
            .saturating_add(RocksDbWeight::get().writes(13_u64))
    }
    fn vote() -> Weight {
        Weight::from_parts(381_801_000, 14005)
            .saturating_add(RocksDbWeight::get().reads(18_u64))
            .saturating_add(RocksDbWeight::get().writes(14_u64))
    }
    fn close_dispute() -> Weight {
        Weight::from_parts(95_449_000, 8652)
            .saturating_add(RocksDbWeight::get().reads(8_u64))
            .saturating_add(RocksDbWeight::get().writes(5_u64))
    }
    fn set_stats_config() -> Weight {
        Weight::from_parts(19_795_000, 1488)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn clear_stale(n: u32) -> Weight {
        Weight::from_parts(220_636_946, 8629)
            .saturating_add(Weight::from_parts(1_077_046_326, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().reads((130_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
            .saturating_add(RocksDbWeight::get().writes((129_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 509952).saturating_mul(n.into()))
    }
    fn set_params() -> Weight {
        Weight::from_parts(20_186_000, 1519)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn set_endpoint() -> Weight {
        Weight::from_parts(24_888_000, 3675)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn start_round(n: u32) -> Weight {
        Weight::from_parts(41_532_601, 3675)
            .saturating_add(Weight::from_parts(5_328_700, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
            .saturating_add(Weight::from_parts(0, 2685).saturating_mul(n.into()))
    }
    fn prune(n: u32) -> Weight {
        Weight::from_parts(54_527_000, 4974)
            .saturating_add(Weight::from_parts(19_802_279, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
            .saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 7639).saturating_mul(n.into()))
    }
}
