//! Autogenerated weights for `pallet_evm_support`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-28.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.10GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_evm_support`.
pub trait WeightInfo {
    /// Benchmarked weight of `pq_verify_ml_dsa_44`.
    fn pq_verify_ml_dsa_44(m: u32) -> Weight;
    /// Benchmarked weight of `pq_verify_ml_dsa_65`.
    fn pq_verify_ml_dsa_65(m: u32) -> Weight;
    /// Benchmarked weight of `pq_verify_ml_dsa_87`.
    fn pq_verify_ml_dsa_87(m: u32) -> Weight;
    /// Benchmarked weight of `pq_verify_rejected`.
    fn pq_verify_rejected() -> Weight;
    /// Benchmarked weight of `blake3`.
    fn blake3(n: u32) -> Weight;
    /// Benchmarked weight of `poseidon2`.
    fn poseidon2(n: u32) -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn pq_verify_ml_dsa_44(m: u32) -> Weight {
        Weight::from_parts(459_980_294, 0)
            .saturating_add(Weight::from_parts(8_366, 0).saturating_mul(m.into()))
    }
    fn pq_verify_ml_dsa_65(m: u32) -> Weight {
        Weight::from_parts(707_030_626, 0)
            .saturating_add(Weight::from_parts(17_718, 0).saturating_mul(m.into()))
    }
    fn pq_verify_ml_dsa_87(m: u32) -> Weight {
        Weight::from_parts(1_248_328_536, 0)
            .saturating_add(Weight::from_parts(2_072, 0).saturating_mul(m.into()))
    }
    fn pq_verify_rejected() -> Weight {
        Weight::from_parts(523_000, 0)
    }
    fn blake3(n: u32) -> Weight {
        Weight::from_parts(576_000, 0)
            .saturating_add(Weight::from_parts(3_174, 0).saturating_mul(n.into()))
    }
    fn poseidon2(n: u32) -> Weight {
        Weight::from_parts(17_655_844, 0)
            .saturating_add(Weight::from_parts(60_603, 0).saturating_mul(n.into()))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn pq_verify_ml_dsa_44(m: u32) -> Weight {
        Weight::from_parts(459_980_294, 0)
            .saturating_add(Weight::from_parts(8_366, 0).saturating_mul(m.into()))
    }
    fn pq_verify_ml_dsa_65(m: u32) -> Weight {
        Weight::from_parts(707_030_626, 0)
            .saturating_add(Weight::from_parts(17_718, 0).saturating_mul(m.into()))
    }
    fn pq_verify_ml_dsa_87(m: u32) -> Weight {
        Weight::from_parts(1_248_328_536, 0)
            .saturating_add(Weight::from_parts(2_072, 0).saturating_mul(m.into()))
    }
    fn pq_verify_rejected() -> Weight {
        Weight::from_parts(523_000, 0)
    }
    fn blake3(n: u32) -> Weight {
        Weight::from_parts(576_000, 0)
            .saturating_add(Weight::from_parts(3_174, 0).saturating_mul(n.into()))
    }
    fn poseidon2(n: u32) -> Weight {
        Weight::from_parts(17_655_844, 0)
            .saturating_add(Weight::from_parts(60_603, 0).saturating_mul(n.into()))
    }
}
