//! Autogenerated weights for `pallet_randomness_cr`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-27.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_randomness_cr`.
pub trait WeightInfo {
    /// Benchmarked weight of `note_randomness`.
    fn note_randomness() -> Weight;
    /// Benchmarked weight of `conclude_epoch`.
    fn conclude_epoch(r: u32) -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `RandomnessCr::Commits` (r:2 w:1)
    /// Proof: `RandomnessCr::Commits` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    /// Storage: `RandomnessCr::Reveals` (r:1 w:1)
    /// Proof: `RandomnessCr::Reveals` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    fn note_randomness() -> Weight {
        Weight::from_parts(16_904_000, 6132)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `RandomnessCr::Reveals` (r:101 w:100)
    /// Proof: `RandomnessCr::Reveals` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    /// Storage: `RandomnessCr::Commits` (r:101 w:100)
    /// Proof: `RandomnessCr::Commits` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    /// Storage: `RandomnessCr::Latest` (r:0 w:1)
    /// Proof: `RandomnessCr::Latest` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `RandomnessCr::LastMissed` (r:0 w:1)
    /// Proof: `RandomnessCr::LastMissed` (`max_values`: Some(1), `max_size`: Some(3210), added: 3705, mode: `MaxEncodedLen`)
    /// Storage: `RandomnessCr::Randomness` (r:0 w:1)
    /// Proof: `RandomnessCr::Randomness` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
    /// Storage: `RandomnessCr::MissedReveals` (r:3 w:3)
    /// Proof: `RandomnessCr::MissedReveals` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
    fn conclude_epoch(r: u32) -> Weight {
        Weight::from_parts(915_566_009, 260661)
            .saturating_add(Weight::from_parts(3_121_676, 0).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(202_u64))
            .saturating_add(T::DbWeight::get().writes(203_u64))
            .saturating_add(Weight::from_parts(0, 2571).saturating_mul(r.into()))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn note_randomness() -> Weight {
        Weight::from_parts(16_904_000, 6132)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn conclude_epoch(r: u32) -> Weight {
        Weight::from_parts(915_566_009, 260661)
            .saturating_add(Weight::from_parts(3_121_676, 0).saturating_mul(r.into()))
            .saturating_add(RocksDbWeight::get().reads(202_u64))
            .saturating_add(RocksDbWeight::get().writes(203_u64))
            .saturating_add(Weight::from_parts(0, 2571).saturating_mul(r.into()))
    }
}
