//! Autogenerated weights for `pallet_validator_set`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-26.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_validator_set`.
pub trait WeightInfo {
    /// Benchmarked weight of `epoch_boundary_with_change`.
    fn epoch_boundary_with_change(n: u32) -> Weight;
    /// Benchmarked weight of `epoch_boundary_without_change`.
    fn epoch_boundary_without_change(n: u32) -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `ValidatorSet::PendingRemovals` (r:1 w:1)
    /// Proof: `ValidatorSet::PendingRemovals` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::CurrentSetId` (r:1 w:1)
    /// Proof: `ValidatorSet::CurrentSetId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::OldestSet` (r:1 w:1)
    /// Proof: `ValidatorSet::OldestSet` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::SetHistory` (r:1 w:2)
    /// Proof: `ValidatorSet::SetHistory` (`max_values`: None, `max_size`: Some(260126), added: 262601, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::Authorities` (r:1 w:1)
    /// Proof: `ValidatorSet::Authorities` (`max_values`: Some(1), `max_size`: Some(260102), added: 260597, mode: `MaxEncodedLen`)
    /// Storage: `AuraPq::Authorities` (r:0 w:1)
    /// Proof: `AuraPq::Authorities` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    fn epoch_boundary_with_change(n: u32) -> Weight {
        Weight::from_parts(62_916_666, 263591)
            .saturating_add(Weight::from_parts(18_341_289, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    /// Storage: `ValidatorSet::PendingRemovals` (r:1 w:0)
    /// Proof: `ValidatorSet::PendingRemovals` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::CurrentSetId` (r:1 w:0)
    /// Proof: `ValidatorSet::CurrentSetId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::OldestSet` (r:1 w:1)
    /// Proof: `ValidatorSet::OldestSet` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::SetHistory` (r:1 w:1)
    /// Proof: `ValidatorSet::SetHistory` (`max_values`: None, `max_size`: Some(260126), added: 262601, mode: `MaxEncodedLen`)
    fn epoch_boundary_without_change(n: u32) -> Weight {
        Weight::from_parts(24_353_299, 263591)
            .saturating_add(Weight::from_parts(1_974_499, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn epoch_boundary_with_change(n: u32) -> Weight {
        Weight::from_parts(62_916_666, 263591)
            .saturating_add(Weight::from_parts(18_341_289, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(7_u64))
    }
    fn epoch_boundary_without_change(n: u32) -> Weight {
        Weight::from_parts(24_353_299, 263591)
            .saturating_add(Weight::from_parts(1_974_499, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
}
