//! Autogenerated weights for `pallet_validator_set`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-27.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_validator_set`.
pub trait WeightInfo {
    /// Benchmarked weight of `epoch_boundary_with_change`.
    fn epoch_boundary_with_change(n: u32) -> Weight;
    /// Benchmarked weight of `epoch_boundary_without_change`.
    fn epoch_boundary_without_change(n: u32) -> Weight;
    /// Benchmarked weight of `add_poa_authority`.
    fn add_poa_authority() -> Weight;
    /// Benchmarked weight of `remove_poa_authority`.
    fn remove_poa_authority() -> Weight;
    /// Benchmarked weight of `set_validator_count`.
    fn set_validator_count() -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `ValidatorSet::PendingRemovals` (r:1 w:1)
    /// Proof: `ValidatorSet::PendingRemovals` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::CurrentSetId` (r:1 w:1)
    /// Proof: `ValidatorSet::CurrentSetId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::OldestSet` (r:1 w:1)
    /// Proof: `ValidatorSet::OldestSet` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::SetHistory` (r:1 w:2)
    /// Proof: `ValidatorSet::SetHistory` (`max_values`: None, `max_size`: Some(260126), added: 262601, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::Authorities` (r:1 w:1)
    /// Proof: `ValidatorSet::Authorities` (`max_values`: Some(1), `max_size`: Some(260102), added: 260597, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::ValidatorCount` (r:1 w:0)
    /// Proof: `ValidatorSet::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::Phase` (r:1 w:0)
    /// Proof: `ValidatorSet::Phase` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:1 w:0)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Candidates` (r:1 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::QualifiedSince` (r:1 w:1)
    /// Proof: `ValidatorSet::QualifiedSince` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::TransitionParams` (r:1 w:0)
    /// Proof: `ValidatorSet::TransitionParams` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::PoaAuthorities` (r:1 w:1)
    /// Proof: `ValidatorSet::PoaAuthorities` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    /// Storage: `AuraPq::Authorities` (r:0 w:1)
    /// Proof: `AuraPq::Authorities` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    fn epoch_boundary_with_change(n: u32) -> Weight {
        Weight::from_parts(122_978_847, 263591)
            .saturating_add(Weight::from_parts(20_746_029, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(12_u64))
            .saturating_add(T::DbWeight::get().writes(9_u64))
    }
    /// Storage: `ValidatorSet::PendingRemovals` (r:1 w:0)
    /// Proof: `ValidatorSet::PendingRemovals` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::CurrentSetId` (r:1 w:0)
    /// Proof: `ValidatorSet::CurrentSetId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::OldestSet` (r:1 w:1)
    /// Proof: `ValidatorSet::OldestSet` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::SetHistory` (r:1 w:1)
    /// Proof: `ValidatorSet::SetHistory` (`max_values`: None, `max_size`: Some(260126), added: 262601, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::Authorities` (r:1 w:0)
    /// Proof: `ValidatorSet::Authorities` (`max_values`: Some(1), `max_size`: Some(260102), added: 260597, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::ValidatorCount` (r:1 w:0)
    /// Proof: `ValidatorSet::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::Phase` (r:1 w:0)
    /// Proof: `ValidatorSet::Phase` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:1 w:0)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Candidates` (r:1 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::QualifiedSince` (r:1 w:1)
    /// Proof: `ValidatorSet::QualifiedSince` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::TransitionParams` (r:1 w:0)
    /// Proof: `ValidatorSet::TransitionParams` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::PoaAuthorities` (r:1 w:1)
    /// Proof: `ValidatorSet::PoaAuthorities` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    fn epoch_boundary_without_change(n: u32) -> Weight {
        Weight::from_parts(78_542_386, 263591)
            .saturating_add(Weight::from_parts(11_311_060, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(12_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `ValidatorSet::Phase` (r:1 w:0)
    /// Proof: `ValidatorSet::Phase` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::PoaAuthorities` (r:1 w:1)
    /// Proof: `ValidatorSet::PoaAuthorities` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::EpochLength` (r:1 w:0)
    /// Proof: `ValidatorSet::EpochLength` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn add_poa_authority() -> Weight {
        Weight::from_parts(485_785_000, 260787)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ValidatorSet::Phase` (r:1 w:0)
    /// Proof: `ValidatorSet::Phase` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::PoaAuthorities` (r:1 w:1)
    /// Proof: `ValidatorSet::PoaAuthorities` (`max_values`: Some(1), `max_size`: Some(259302), added: 259797, mode: `MaxEncodedLen`)
    fn remove_poa_authority() -> Weight {
        Weight::from_parts(474_999_000, 260787)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ValidatorSet::TransitionParams` (r:1 w:0)
    /// Proof: `ValidatorSet::TransitionParams` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::EpochLength` (r:1 w:0)
    /// Proof: `ValidatorSet::EpochLength` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `ValidatorSet::ValidatorCount` (r:0 w:1)
    /// Proof: `ValidatorSet::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn set_validator_count() -> Weight {
        Weight::from_parts(11_780_000, 1509)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn epoch_boundary_with_change(n: u32) -> Weight {
        Weight::from_parts(122_978_847, 263591)
            .saturating_add(Weight::from_parts(20_746_029, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(12_u64))
            .saturating_add(RocksDbWeight::get().writes(9_u64))
    }
    fn epoch_boundary_without_change(n: u32) -> Weight {
        Weight::from_parts(78_542_386, 263591)
            .saturating_add(Weight::from_parts(11_311_060, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(12_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
    fn add_poa_authority() -> Weight {
        Weight::from_parts(485_785_000, 260787)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn remove_poa_authority() -> Weight {
        Weight::from_parts(474_999_000, 260787)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn set_validator_count() -> Weight {
        Weight::from_parts(11_780_000, 1509)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
