//! Autogenerated weights for `pallet_emission`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-27.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.10GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_emission`.
pub trait WeightInfo {
    /// Benchmarked weight of `settle_epoch`.
    fn settle_epoch() -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Emission::Reserve` (r:1 w:1)
    /// Proof: `Emission::Reserve` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `TreasuryDual::CommunityShare` (r:1 w:0)
    /// Proof: `TreasuryDual::CommunityShare` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `TreasuryDual::FloorBatches` (r:1 w:1)
    /// Proof: `TreasuryDual::FloorBatches` (`max_values`: Some(1), `max_size`: Some(625), added: 1120, mode: `MaxEncodedLen`)
    /// Storage: `TreasuryDual::FloorMatured` (r:1 w:1)
    /// Proof: `TreasuryDual::FloorMatured` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Emission::TotalMinted` (r:1 w:1)
    /// Proof: `Emission::TotalMinted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Emission::LastSettled` (r:0 w:1)
    /// Proof: `Emission::LastSettled` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn settle_epoch() -> Weight {
        Weight::from_parts(41_196_000, 3593)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn settle_epoch() -> Weight {
        Weight::from_parts(41_196_000, 3593)
            .saturating_add(RocksDbWeight::get().reads(6_u64))
            .saturating_add(RocksDbWeight::get().writes(6_u64))
    }
}
