//! Autogenerated weights for `pallet_emission`.
//!
//! Placeholder until the benchmarks run (m3-economics 4.2). Do not edit by hand: re-run the
//! benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_emission`.
pub trait WeightInfo {
    /// Benchmarked weight of `settle_epoch`.
    fn settle_epoch() -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn settle_epoch() -> Weight {
        Weight::from_parts(100_000_000, 10_000)
            .saturating_add(T::DbWeight::get().reads(10_u64))
            .saturating_add(T::DbWeight::get().writes(10_u64))
    }
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    fn settle_epoch() -> Weight {
        Weight::from_parts(100_000_000, 10_000)
            .saturating_add(RocksDbWeight::get().reads(10_u64))
            .saturating_add(RocksDbWeight::get().writes(10_u64))
    }
}
