#!/usr/bin/env python3
"""Generate and check security-advisory ignore lists from audit-exceptions.toml.

Usage:
  scripts/sync-audit-exceptions.py            check (CI): fields, review dates, generated files
  scripts/sync-audit-exceptions.py --write    regenerate deny.toml's ignore list and .cargo/audit.toml

Rules (spec engineering/ci-quality-gates, "安全公告例外须逐条记录"):
  * every exception has id, crate, path, reason, added and review_by;
  * review_by is at most 90 days after added and not earlier than today;
  * optional `scope`: "both" (default) or "audit" — the latter only for advisories that
    cargo-audit reports from Cargo.lock but cargo-deny does not see in the compiled graph.
"""

from __future__ import annotations

import datetime as dt
import pathlib
import re
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXCEPTIONS = ROOT / "audit-exceptions.toml"
DENY = ROOT / "deny.toml"
AUDIT = ROOT / ".cargo" / "audit.toml"
REQUIRED = ("id", "crate", "path", "reason", "added", "review_by")
MAX_REVIEW_DAYS = 90
BEGIN = "# BEGIN generated by scripts/sync-audit-exceptions.py — edit audit-exceptions.toml instead"
END = "# END generated"


def validate(entries: list[dict], today: dt.date) -> list[str]:
    """Returns a list of human-readable problems (empty when valid)."""
    problems = []
    seen = set()
    for i, e in enumerate(entries):
        label = e.get("id", f"entry #{i + 1}")
        for field in REQUIRED:
            value = e.get(field)
            if not isinstance(value, (str, dt.date)) or not str(value).strip():
                problems.append(f"{label}: missing or empty '{field}'")
        if not re.fullmatch(r"RUSTSEC-\d{4}-\d{4}", str(e.get("id", ""))):
            problems.append(f"{label}: id must look like RUSTSEC-YYYY-NNNN")
        if e.get("scope", "both") not in ("both", "audit"):
            problems.append(f"{label}: scope must be 'both' or 'audit'")
        if label in seen:
            problems.append(f"{label}: duplicate entry")
        seen.add(label)
        try:
            added = dt.date.fromisoformat(str(e.get("added")))
            review = dt.date.fromisoformat(str(e.get("review_by")))
        except ValueError:
            problems.append(f"{label}: 'added' and 'review_by' must be YYYY-MM-DD dates")
            continue
        if (review - added).days > MAX_REVIEW_DAYS:
            problems.append(f"{label}: review_by is more than {MAX_REVIEW_DAYS} days after added")
        if review < today:
            problems.append(f"{label}: review date {review} has passed; review and renew or remove it")
    return problems


def deny_block(entries: list[dict]) -> str:
    lines = [BEGIN, "ignore = ["]
    for e in (e for e in entries if e.get("scope", "both") == "both"):
        reason = str(e["reason"]).split(". ")[0].replace('"', "'")
        lines.append(f'    {{ id = "{e["id"]}", reason = "{reason} (see audit-exceptions.toml)" }},')
    lines += ["]", END]
    return "\n".join(lines)


def audit_toml(entries: list[dict]) -> str:
    ids = ",\n".join(f'    "{e["id"]}"' for e in entries)
    return (
        "# Generated by scripts/sync-audit-exceptions.py from audit-exceptions.toml; do not edit.\n"
        f"[advisories]\nignore = [\n{ids},\n]\n"
    )


def render_deny(current: str, entries: list[dict]) -> str:
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(current):
        raise SystemExit(f"{DENY} lacks the generated ignore block markers")
    return pattern.sub(lambda _: deny_block(entries), current)


def main(argv: list[str]) -> int:
    entries = tomllib.loads(EXCEPTIONS.read_text()).get("exception", [])
    problems = validate(entries, dt.date.today())
    if problems:
        print("audit exceptions invalid:\n  " + "\n  ".join(problems), file=sys.stderr)
        return 1
    deny_new = render_deny(DENY.read_text(), entries)
    audit_new = audit_toml(entries)
    if "--write" in argv:
        DENY.write_text(deny_new)
        AUDIT.parent.mkdir(exist_ok=True)
        AUDIT.write_text(audit_new)
        print("regenerated deny.toml and .cargo/audit.toml")
        return 0
    stale = [p.name for p, new in ((DENY, deny_new), (AUDIT, audit_new))
             if not p.exists() or p.read_text() != new]
    if stale:
        print(f"out of sync with audit-exceptions.toml: {', '.join(stale)}; run with --write",
              file=sys.stderr)
        return 1
    print(f"{len(entries)} audit exceptions valid and in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
