//! Autogenerated weights for `pallet_staking_pos`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-27.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_staking_pos`.
pub trait WeightInfo {
    /// Benchmarked weight of `register_candidate`.
    fn register_candidate(c: u32) -> Weight;
    /// Benchmarked weight of `bond_extra`.
    fn bond_extra() -> Weight;
    /// Benchmarked weight of `set_validator_key`.
    fn set_validator_key() -> Weight;
    /// Benchmarked weight of `retire`.
    fn retire() -> Weight;
    /// Benchmarked weight of `nominate`.
    fn nominate(n: u32) -> Weight;
    /// Benchmarked weight of `set_nominations`.
    fn set_nominations() -> Weight;
    /// Benchmarked weight of `unnominate`.
    fn unnominate() -> Weight;
    /// Benchmarked weight of `unbond`.
    fn unbond() -> Weight;
    /// Benchmarked weight of `withdraw_unbonded`.
    fn withdraw_unbonded() -> Weight;
    /// Benchmarked weight of `set_commission`.
    fn set_commission() -> Weight;
    /// Benchmarked weight of `chill`.
    fn chill() -> Weight;
    /// Benchmarked weight of `validate`.
    fn validate() -> Weight;
    /// Benchmarked weight of `elect`.
    fn elect(c: u32, n: u32, s: u32) -> Weight;
    /// Benchmarked weight of `transition_inputs`.
    fn transition_inputs(c: u32, n: u32) -> Weight;
    /// Benchmarked weight of `close_epoch`.
    fn close_epoch(p: u32, m: u32) -> Weight;
    /// Benchmarked weight of `note_author`.
    fn note_author() -> Weight;
    /// Benchmarked weight of `pay_rewards`.
    fn pay_rewards(n: u32) -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `StakingPos::Candidates` (r:502 w:2)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Nominators` (r:1 w:0)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:501 w:2)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::KeyOwner` (r:1 w:1)
    /// Proof: `StakingPos::KeyOwner` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::CounterForCandidates` (r:1 w:1)
    /// Proof: `StakingPos::CounterForCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn register_candidate(c: u32) -> Weight {
        Weight::from_parts(1_115_945_076, 11226)
            .saturating_add(Weight::from_parts(6_731_496, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(11_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(c.into())))
            .saturating_add(T::DbWeight::get().writes(9_u64))
            .saturating_add(Weight::from_parts(0, 5118).saturating_mul(c.into()))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:1 w:1)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn bond_extra() -> Weight {
        Weight::from_parts(75_408_000, 6108)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:1)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::KeyOwner` (r:1 w:1)
    /// Proof: `StakingPos::KeyOwner` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    fn set_validator_key() -> Weight {
        Weight::from_parts(1_006_465_000, 6108)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:1)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::CounterForCandidates` (r:1 w:1)
    /// Proof: `StakingPos::CounterForCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:1 w:1)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn retire() -> Weight {
        Weight::from_parts(40_519_000, 6108)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:17 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Nominators` (r:2002 w:2)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:2001 w:2)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::CounterForNominators` (r:1 w:1)
    /// Proof: `StakingPos::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::UnbondQueueEnd` (r:1 w:1)
    /// Proof: `StakingPos::UnbondQueueEnd` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn nominate(n: u32) -> Weight {
        Weight::from_parts(176_132_000, 87996)
            .saturating_add(Weight::from_parts(7_277_533, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(26_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(9_u64))
            .saturating_add(Weight::from_parts(0, 3292).saturating_mul(n.into()))
    }
    /// Storage: `StakingPos::Nominators` (r:1 w:1)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Candidates` (r:16 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    fn set_nominations() -> Weight {
        Weight::from_parts(75_134_000, 82878)
            .saturating_add(T::DbWeight::get().reads(17_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `StakingPos::Nominators` (r:1 w:1)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::CounterForNominators` (r:1 w:1)
    /// Proof: `StakingPos::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:1 w:1)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::UnbondQueueEnd` (r:1 w:1)
    /// Proof: `StakingPos::UnbondQueueEnd` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn unnominate() -> Weight {
        Weight::from_parts(42_159_000, 4282)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `StakingPos::Ledger` (r:1 w:1)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Candidates` (r:1 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Nominators` (r:1 w:0)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::UnbondQueueEnd` (r:1 w:1)
    /// Proof: `StakingPos::UnbondQueueEnd` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn unbond() -> Weight {
        Weight::from_parts(39_122_000, 6108)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `StakingPos::Ledger` (r:1 w:1)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(51_742_000, 4282)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:1)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    fn set_commission() -> Weight {
        Weight::from_parts(24_394_000, 6108)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:1)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    fn chill() -> Weight {
        Weight::from_parts(22_232_000, 6108)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:1)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:1 w:0)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    fn validate() -> Weight {
        Weight::from_parts(27_390_000, 6108)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:501 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:2500 w:0)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Nominators` (r:2001 w:0)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::LastElection` (r:0 w:1)
    /// Proof: `StakingPos::LastElection` (`max_values`: Some(1), `max_size`: Some(2641011), added: 2641506, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Exposures` (r:0 w:200)
    /// Proof: `StakingPos::Exposures` (`max_values`: None, `max_size`: Some(96082), added: 98557, mode: `MaxEncodedLen`)
    fn elect(c: u32, n: u32, s: u32) -> Weight {
        Weight::from_parts(21_673_978_000, 6108)
            .saturating_add(Weight::from_parts(57_570_648, 0).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(120_120_287, 0).saturating_mul(n.into()))
            .saturating_add(Weight::from_parts(1_117_218_394, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(c.into())))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(2_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
            .saturating_add(Weight::from_parts(0, 5118).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(0, 3292).saturating_mul(n.into()))
    }
    /// Storage: `StakingPos::Ledger` (r:2501 w:0)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Candidates` (r:501 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    fn transition_inputs(c: u32, n: u32) -> Weight {
        Weight::from_parts(6_091_292_000, 6108)
            .saturating_add(Weight::from_parts(6_408_813, 0).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(3_377_267, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(c.into())))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 5118).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(0, 3292).saturating_mul(n.into()))
    }
    /// Storage: `StakingPos::EpochPoints` (r:1001 w:1000)
    /// Proof: `StakingPos::EpochPoints` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::MissStreak` (r:1000 w:1000)
    /// Proof: `StakingPos::MissStreak` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::KeyOwner` (r:1000 w:0)
    /// Proof: `StakingPos::KeyOwner` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Candidates` (r:1000 w:1000)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::PendingPoints` (r:21 w:21)
    /// Proof: `StakingPos::PendingPoints` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    fn close_epoch(p: u32, m: u32) -> Weight {
        Weight::from_parts(6_366_079_118, 2539990)
            .saturating_add(Weight::from_parts(5_864_120, 0).saturating_mul(p.into()))
            .saturating_add(Weight::from_parts(11_364_212, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(2001_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(p.into())))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(m.into())))
            .saturating_add(T::DbWeight::get().writes(2000_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
            .saturating_add(Weight::from_parts(0, 5118).saturating_mul(m.into()))
            .saturating_add(Weight::from_parts(0, 2516).saturating_mul(p.into()))
    }
    /// Storage: `StakingPos::EpochPoints` (r:1 w:1)
    /// Proof: `StakingPos::EpochPoints` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
    fn note_author() -> Weight {
        Weight::from_parts(16_159_000, 3501)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `StakingPos::PayoutHead` (r:1 w:1)
    /// Proof: `StakingPos::PayoutHead` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::PayoutTail` (r:1 w:0)
    /// Proof: `StakingPos::PayoutTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Payouts` (r:256 w:256)
    /// Proof: `StakingPos::Payouts` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:257 w:257)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn pay_rewards(n: u32) -> Weight {
        Weight::from_parts(63_317_119, 3593)
            .saturating_add(Weight::from_parts(48_666_448, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(2_u64))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2603).saturating_mul(n.into()))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn register_candidate(c: u32) -> Weight {
        Weight::from_parts(1_115_945_076, 11226)
            .saturating_add(Weight::from_parts(6_731_496, 0).saturating_mul(c.into()))
            .saturating_add(RocksDbWeight::get().reads(11_u64))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(c.into())))
            .saturating_add(RocksDbWeight::get().writes(9_u64))
            .saturating_add(Weight::from_parts(0, 5118).saturating_mul(c.into()))
    }
    fn bond_extra() -> Weight {
        Weight::from_parts(75_408_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
    fn set_validator_key() -> Weight {
        Weight::from_parts(1_006_465_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn retire() -> Weight {
        Weight::from_parts(40_519_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
    fn nominate(n: u32) -> Weight {
        Weight::from_parts(176_132_000, 87996)
            .saturating_add(Weight::from_parts(7_277_533, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(26_u64))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(9_u64))
            .saturating_add(Weight::from_parts(0, 3292).saturating_mul(n.into()))
    }
    fn set_nominations() -> Weight {
        Weight::from_parts(75_134_000, 82878)
            .saturating_add(RocksDbWeight::get().reads(17_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn unnominate() -> Weight {
        Weight::from_parts(42_159_000, 4282)
            .saturating_add(RocksDbWeight::get().reads(6_u64))
            .saturating_add(RocksDbWeight::get().writes(5_u64))
    }
    fn unbond() -> Weight {
        Weight::from_parts(39_122_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(6_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(51_742_000, 4282)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn set_commission() -> Weight {
        Weight::from_parts(24_394_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn chill() -> Weight {
        Weight::from_parts(22_232_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn validate() -> Weight {
        Weight::from_parts(27_390_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn elect(c: u32, n: u32, s: u32) -> Weight {
        Weight::from_parts(21_673_978_000, 6108)
            .saturating_add(Weight::from_parts(57_570_648, 0).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(120_120_287, 0).saturating_mul(n.into()))
            .saturating_add(Weight::from_parts(1_117_218_394, 0).saturating_mul(s.into()))
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(c.into())))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(s.into())))
            .saturating_add(Weight::from_parts(0, 5118).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(0, 3292).saturating_mul(n.into()))
    }
    fn transition_inputs(c: u32, n: u32) -> Weight {
        Weight::from_parts(6_091_292_000, 6108)
            .saturating_add(Weight::from_parts(6_408_813, 0).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(3_377_267, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(c.into())))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 5118).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(0, 3292).saturating_mul(n.into()))
    }
    fn close_epoch(p: u32, m: u32) -> Weight {
        Weight::from_parts(6_366_079_118, 2539990)
            .saturating_add(Weight::from_parts(5_864_120, 0).saturating_mul(p.into()))
            .saturating_add(Weight::from_parts(11_364_212, 0).saturating_mul(m.into()))
            .saturating_add(RocksDbWeight::get().reads(2001_u64))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(p.into())))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(m.into())))
            .saturating_add(RocksDbWeight::get().writes(2000_u64))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(p.into())))
            .saturating_add(Weight::from_parts(0, 5118).saturating_mul(m.into()))
            .saturating_add(Weight::from_parts(0, 2516).saturating_mul(p.into()))
    }
    fn note_author() -> Weight {
        Weight::from_parts(16_159_000, 3501)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn pay_rewards(n: u32) -> Weight {
        Weight::from_parts(63_317_119, 3593)
            .saturating_add(Weight::from_parts(48_666_448, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
            .saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2603).saturating_mul(n.into()))
    }
}
