//! Autogenerated weights for `pallet_staking_pos`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-27.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_staking_pos`.
pub trait WeightInfo {
    /// Benchmarked weight of `register_candidate`.
    fn register_candidate(c: u32) -> Weight;
    /// Benchmarked weight of `bond_extra`.
    fn bond_extra() -> Weight;
    /// Benchmarked weight of `set_validator_key`.
    fn set_validator_key() -> Weight;
    /// Benchmarked weight of `retire`.
    fn retire() -> Weight;
    /// Benchmarked weight of `nominate`.
    fn nominate(n: u32) -> Weight;
    /// Benchmarked weight of `set_nominations`.
    fn set_nominations() -> Weight;
    /// Benchmarked weight of `unnominate`.
    fn unnominate() -> Weight;
    /// Benchmarked weight of `unbond`.
    fn unbond() -> Weight;
    /// Benchmarked weight of `withdraw_unbonded`.
    fn withdraw_unbonded() -> Weight;
    /// Benchmarked weight of `set_commission`.
    fn set_commission() -> Weight;
    /// Benchmarked weight of `chill`.
    fn chill() -> Weight;
    /// Benchmarked weight of `validate`.
    fn validate() -> Weight;
    /// Benchmarked weight of `elect`.
    fn elect(c: u32, n: u32, s: u32) -> Weight;
    /// Benchmarked weight of `transition_inputs`.
    fn transition_inputs(c: u32, n: u32) -> Weight;
    /// Benchmarked weight of `close_epoch`.
    fn close_epoch(p: u32, m: u32) -> Weight;
    /// Benchmarked weight of `note_author`.
    fn note_author() -> Weight;
    /// Benchmarked weight of `pay_rewards`.
    fn pay_rewards(n: u32) -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `StakingPos::Candidates` (r:502 w:2)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Nominators` (r:1 w:0)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:501 w:2)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::KeyOwner` (r:1 w:1)
    /// Proof: `StakingPos::KeyOwner` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::CounterForCandidates` (r:1 w:1)
    /// Proof: `StakingPos::CounterForCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn register_candidate(c: u32) -> Weight {
        Weight::from_parts(1_122_599_217, 11226)
            .saturating_add(Weight::from_parts(6_606_752, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(11_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(c.into())))
            .saturating_add(T::DbWeight::get().writes(9_u64))
            .saturating_add(Weight::from_parts(0, 5118).saturating_mul(c.into()))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:1 w:1)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn bond_extra() -> Weight {
        Weight::from_parts(73_901_000, 6108)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:1)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::KeyOwner` (r:1 w:1)
    /// Proof: `StakingPos::KeyOwner` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    fn set_validator_key() -> Weight {
        Weight::from_parts(998_312_000, 6108)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:1)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::CounterForCandidates` (r:1 w:1)
    /// Proof: `StakingPos::CounterForCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:1 w:1)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn retire() -> Weight {
        Weight::from_parts(40_278_000, 6108)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:17 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Nominators` (r:2002 w:2)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:2001 w:2)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::CounterForNominators` (r:1 w:1)
    /// Proof: `StakingPos::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::UnbondQueueEnd` (r:1 w:1)
    /// Proof: `StakingPos::UnbondQueueEnd` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn nominate(n: u32) -> Weight {
        Weight::from_parts(167_534_000, 87996)
            .saturating_add(Weight::from_parts(7_125_158, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(26_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(9_u64))
            .saturating_add(Weight::from_parts(0, 3292).saturating_mul(n.into()))
    }
    /// Storage: `StakingPos::Nominators` (r:1 w:1)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Candidates` (r:16 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    fn set_nominations() -> Weight {
        Weight::from_parts(74_537_000, 82878)
            .saturating_add(T::DbWeight::get().reads(17_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `StakingPos::Nominators` (r:1 w:1)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::CounterForNominators` (r:1 w:1)
    /// Proof: `StakingPos::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:1 w:1)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::UnbondQueueEnd` (r:1 w:1)
    /// Proof: `StakingPos::UnbondQueueEnd` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn unnominate() -> Weight {
        Weight::from_parts(43_176_000, 4282)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `StakingPos::Ledger` (r:1 w:1)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Candidates` (r:1 w:0)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Nominators` (r:1 w:0)
    /// Proof: `StakingPos::Nominators` (`max_values`: None, `max_size`: Some(545), added: 3020, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::UnbondQueueEnd` (r:1 w:1)
    /// Proof: `StakingPos::UnbondQueueEnd` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::TotalActive` (r:1 w:1)
    /// Proof: `StakingPos::TotalActive` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn unbond() -> Weight {
        Weight::from_parts(40_052_000, 6108)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `StakingPos::Ledger` (r:1 w:1)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(50_580_000, 4282)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:1)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Params` (r:1 w:0)
    /// Proof: `StakingPos::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    fn set_commission() -> Weight {
        Weight::from_parts(26_015_000, 6108)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:1)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    fn chill() -> Weight {
        Weight::from_parts(23_225_000, 6108)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `StakingPos::Candidates` (r:1 w:1)
    /// Proof: `StakingPos::Candidates` (`max_values`: None, `max_size`: Some(2643), added: 5118, mode: `MaxEncodedLen`)
    /// Storage: `StakingPos::Ledger` (r:1 w:0)
    /// Proof: `StakingPos::Ledger` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
    fn validate() -> Weight {
        Weight::from_parts(30_075_000, 6108)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    fn elect(_c: u32, _n: u32, _s: u32) -> Weight {
        Weight::zero()
    }
    fn transition_inputs(_c: u32, _n: u32) -> Weight {
        Weight::zero()
    }
    fn close_epoch(_p: u32, _m: u32) -> Weight {
        Weight::zero()
    }
    fn note_author() -> Weight {
        Weight::zero()
    }
    fn pay_rewards(_n: u32) -> Weight {
        Weight::zero()
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn register_candidate(c: u32) -> Weight {
        Weight::from_parts(1_122_599_217, 11226)
            .saturating_add(Weight::from_parts(6_606_752, 0).saturating_mul(c.into()))
            .saturating_add(RocksDbWeight::get().reads(11_u64))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(c.into())))
            .saturating_add(RocksDbWeight::get().writes(9_u64))
            .saturating_add(Weight::from_parts(0, 5118).saturating_mul(c.into()))
    }
    fn bond_extra() -> Weight {
        Weight::from_parts(73_901_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
    fn set_validator_key() -> Weight {
        Weight::from_parts(998_312_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn retire() -> Weight {
        Weight::from_parts(40_278_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
    fn nominate(n: u32) -> Weight {
        Weight::from_parts(167_534_000, 87996)
            .saturating_add(Weight::from_parts(7_125_158, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(26_u64))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(9_u64))
            .saturating_add(Weight::from_parts(0, 3292).saturating_mul(n.into()))
    }
    fn set_nominations() -> Weight {
        Weight::from_parts(74_537_000, 82878)
            .saturating_add(RocksDbWeight::get().reads(17_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn unnominate() -> Weight {
        Weight::from_parts(43_176_000, 4282)
            .saturating_add(RocksDbWeight::get().reads(6_u64))
            .saturating_add(RocksDbWeight::get().writes(5_u64))
    }
    fn unbond() -> Weight {
        Weight::from_parts(40_052_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(6_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn withdraw_unbonded() -> Weight {
        Weight::from_parts(50_580_000, 4282)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn set_commission() -> Weight {
        Weight::from_parts(26_015_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn chill() -> Weight {
        Weight::from_parts(23_225_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn validate() -> Weight {
        Weight::from_parts(30_075_000, 6108)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn elect(_c: u32, _n: u32, _s: u32) -> Weight {
        Weight::zero()
    }
    fn transition_inputs(_c: u32, _n: u32) -> Weight {
        Weight::zero()
    }
    fn close_epoch(_p: u32, _m: u32) -> Weight {
        Weight::zero()
    }
    fn note_author() -> Weight {
        Weight::zero()
    }
    fn pay_rewards(_n: u32) -> Weight {
        Weight::zero()
    }
}
