//! Autogenerated weights for `pallet_public_jobs`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-10-02.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.10GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_public_jobs`.
pub trait WeightInfo {
    /// Benchmarked weight of `register`.
    fn register() -> Weight;
    /// Benchmarked weight of `set_models`.
    fn set_models() -> Weight;
    /// Benchmarked weight of `deregister`.
    fn deregister() -> Weight;
    /// Benchmarked weight of `ready`.
    fn ready() -> Weight;
    /// Benchmarked weight of `publish`.
    fn publish() -> Weight;
    /// Benchmarked weight of `cancel`.
    fn cancel() -> Weight;
    /// Benchmarked weight of `commit`.
    fn commit() -> Weight;
    /// Benchmarked weight of `reveal`.
    fn reveal() -> Weight;
    /// Benchmarked weight of `close`.
    fn close() -> Weight;
    /// Benchmarked weight of `reveal_canary`.
    fn reveal_canary() -> Weight;
    /// Benchmarked weight of `claim`.
    fn claim(n: u32) -> Weight;
    /// Benchmarked weight of `withdraw`.
    fn withdraw() -> Weight;
    /// Benchmarked weight of `set_price_cap`.
    fn set_price_cap() -> Weight;
    /// Benchmarked weight of `start_round`.
    fn start_round(w: u32, u: u32) -> Weight;
    /// Benchmarked weight of `prune`.
    fn prune(n: u32) -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `PublicJobs::Workers` (r:1 w:1)
    /// Proof: `PublicJobs::Workers` (`max_values`: None, `max_size`: Some(308), added: 2783, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::WorkerCount` (r:1 w:1)
    /// Proof: `PublicJobs::WorkerCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `ModelRegistry::Models` (r:8 w:0)
    /// Proof: `ModelRegistry::Models` (`max_values`: None, `max_size`: Some(33250), added: 35725, mode: `MaxEncodedLen`)
    fn register() -> Weight {
        Weight::from_parts(30_231_000, 286790)
            .saturating_add(T::DbWeight::get().reads(10_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `PublicJobs::Workers` (r:1 w:1)
    /// Proof: `PublicJobs::Workers` (`max_values`: None, `max_size`: Some(308), added: 2783, mode: `MaxEncodedLen`)
    /// Storage: `ModelRegistry::Models` (r:8 w:0)
    /// Proof: `ModelRegistry::Models` (`max_values`: None, `max_size`: Some(33250), added: 35725, mode: `MaxEncodedLen`)
    fn set_models() -> Weight {
        Weight::from_parts(29_592_000, 286790)
            .saturating_add(T::DbWeight::get().reads(9_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `PublicJobs::Workers` (r:1 w:1)
    /// Proof: `PublicJobs::Workers` (`max_values`: None, `max_size`: Some(308), added: 2783, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Assigned` (r:1 w:0)
    /// Proof: `PublicJobs::Assigned` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::WorkerCount` (r:1 w:1)
    /// Proof: `PublicJobs::WorkerCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn deregister() -> Weight {
        Weight::from_parts(24_764_000, 3773)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `PublicJobs::Params` (r:1 w:0)
    /// Proof: `PublicJobs::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Workers` (r:1 w:1)
    /// Proof: `PublicJobs::Workers` (`max_values`: None, `max_size`: Some(308), added: 2783, mode: `MaxEncodedLen`)
    fn ready() -> Weight {
        Weight::from_parts(15_020_000, 3773)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `PublicJobs::Params` (r:1 w:0)
    /// Proof: `PublicJobs::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    /// Storage: `ModelRegistry::Models` (r:1 w:0)
    /// Proof: `ModelRegistry::Models` (`max_values`: None, `max_size`: Some(33250), added: 35725, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::ActiveJobs` (r:1 w:1)
    /// Proof: `PublicJobs::ActiveJobs` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::NextJob` (r:1 w:1)
    /// Proof: `PublicJobs::NextJob` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Jobs` (r:0 w:1)
    /// Proof: `PublicJobs::Jobs` (`max_values`: None, `max_size`: Some(665), added: 3140, mode: `MaxEncodedLen`)
    fn publish() -> Weight {
        Weight::from_parts(28_293_000, 36715)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `PublicJobs::Jobs` (r:1 w:1)
    /// Proof: `PublicJobs::Jobs` (`max_values`: None, `max_size`: Some(665), added: 3140, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::ActiveJobs` (r:1 w:1)
    /// Proof: `PublicJobs::ActiveJobs` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
    fn cancel() -> Weight {
        Weight::from_parts(22_422_000, 4130)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `PublicJobs::Units` (r:1 w:1)
    /// Proof: `PublicJobs::Units` (`max_values`: None, `max_size`: Some(3613), added: 6088, mode: `MaxEncodedLen`)
    fn commit() -> Weight {
        Weight::from_parts(20_217_000, 7078)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `PublicJobs::Units` (r:1 w:1)
    /// Proof: `PublicJobs::Units` (`max_values`: None, `max_size`: Some(3613), added: 6088, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Jobs` (r:1 w:1)
    /// Proof: `PublicJobs::Jobs` (`max_values`: None, `max_size`: Some(665), added: 3140, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Params` (r:1 w:0)
    /// Proof: `PublicJobs::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Emission::EpochLength` (r:1 w:0)
    /// Proof: `Emission::EpochLength` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Pending` (r:3 w:3)
    /// Proof: `PublicJobs::Pending` (`max_values`: None, `max_size`: Some(801), added: 3276, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Epochs` (r:1 w:1)
    /// Proof: `PublicJobs::Epochs` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Workers` (r:3 w:3)
    /// Proof: `PublicJobs::Workers` (`max_values`: None, `max_size`: Some(308), added: 2783, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::QueueBounds` (r:1 w:1)
    /// Proof: `PublicJobs::QueueBounds` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::SettledQueue` (r:0 w:1)
    /// Proof: `PublicJobs::SettledQueue` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Assigned` (r:0 w:3)
    /// Proof: `PublicJobs::Assigned` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    fn reveal() -> Weight {
        Weight::from_parts(119_068_000, 10818)
            .saturating_add(T::DbWeight::get().reads(13_u64))
            .saturating_add(T::DbWeight::get().writes(14_u64))
    }
    /// Storage: `PublicJobs::Units` (r:1 w:1)
    /// Proof: `PublicJobs::Units` (`max_values`: None, `max_size`: Some(3613), added: 6088, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Jobs` (r:1 w:1)
    /// Proof: `PublicJobs::Jobs` (`max_values`: None, `max_size`: Some(665), added: 3140, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Params` (r:1 w:0)
    /// Proof: `PublicJobs::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Emission::EpochLength` (r:1 w:0)
    /// Proof: `Emission::EpochLength` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Pending` (r:2 w:2)
    /// Proof: `PublicJobs::Pending` (`max_values`: None, `max_size`: Some(801), added: 3276, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Epochs` (r:1 w:1)
    /// Proof: `PublicJobs::Epochs` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Workers` (r:3 w:3)
    /// Proof: `PublicJobs::Workers` (`max_values`: None, `max_size`: Some(308), added: 2783, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::QueueBounds` (r:1 w:1)
    /// Proof: `PublicJobs::QueueBounds` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::SettledQueue` (r:0 w:1)
    /// Proof: `PublicJobs::SettledQueue` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Assigned` (r:0 w:3)
    /// Proof: `PublicJobs::Assigned` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    fn close() -> Weight {
        Weight::from_parts(123_609_000, 9339)
            .saturating_add(T::DbWeight::get().reads(12_u64))
            .saturating_add(T::DbWeight::get().writes(13_u64))
    }
    /// Storage: `PublicJobs::Jobs` (r:1 w:1)
    /// Proof: `PublicJobs::Jobs` (`max_values`: None, `max_size`: Some(665), added: 3140, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Units` (r:1 w:1)
    /// Proof: `PublicJobs::Units` (`max_values`: None, `max_size`: Some(3613), added: 6088, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Params` (r:1 w:0)
    /// Proof: `PublicJobs::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Locked` (r:3 w:3)
    /// Proof: `PublicJobs::Locked` (`max_values`: None, `max_size`: Some(673), added: 3148, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:3 w:3)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:4 w:4)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Emission::TotalBurned` (r:1 w:1)
    /// Proof: `Emission::TotalBurned` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Pending` (r:3 w:3)
    /// Proof: `PublicJobs::Pending` (`max_values`: None, `max_size`: Some(801), added: 3276, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Epochs` (r:32 w:0)
    /// Proof: `PublicJobs::Epochs` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Unclaimed` (r:1 w:1)
    /// Proof: `PublicJobs::Unclaimed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Workers` (r:3 w:3)
    /// Proof: `PublicJobs::Workers` (`max_values`: None, `max_size`: Some(308), added: 2783, mode: `MaxEncodedLen`)
    fn reveal_canary() -> Weight {
        Weight::from_parts(1_999_760_000, 81758)
            .saturating_add(T::DbWeight::get().reads(53_u64))
            .saturating_add(T::DbWeight::get().writes(20_u64))
    }
    /// Storage: `PublicJobs::Params` (r:1 w:0)
    /// Proof: `PublicJobs::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Locked` (r:1 w:1)
    /// Proof: `PublicJobs::Locked` (`max_values`: None, `max_size`: Some(673), added: 3148, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Pending` (r:1 w:1)
    /// Proof: `PublicJobs::Pending` (`max_values`: None, `max_size`: Some(801), added: 3276, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Epochs` (r:16 w:0)
    /// Proof: `PublicJobs::Epochs` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Unclaimed` (r:1 w:1)
    /// Proof: `PublicJobs::Unclaimed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn claim(n: u32) -> Weight {
        Weight::from_parts(105_249_504, 6196)
            .saturating_add(Weight::from_parts(4_463_000, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(6_u64))
            .saturating_add(Weight::from_parts(0, 2524).saturating_mul(n.into()))
    }
    /// Storage: `PublicJobs::Locked` (r:1 w:1)
    /// Proof: `PublicJobs::Locked` (`max_values`: None, `max_size`: Some(673), added: 3148, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(283), added: 2758, mode: `MaxEncodedLen`)
    fn withdraw() -> Weight {
        Weight::from_parts(50_822_000, 4138)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `PublicJobs::Params` (r:1 w:1)
    /// Proof: `PublicJobs::Params` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
    fn set_price_cap() -> Weight {
        Weight::from_parts(12_326_000, 1533)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `PublicJobs::Workers` (r:1001 w:0)
    /// Proof: `PublicJobs::Workers` (`max_values`: None, `max_size`: Some(308), added: 2783, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Pending` (r:1000 w:0)
    /// Proof: `PublicJobs::Pending` (`max_values`: None, `max_size`: Some(801), added: 3276, mode: `MaxEncodedLen`)
    /// Storage: `RandomnessCr::Latest` (r:1 w:0)
    /// Proof: `RandomnessCr::Latest` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Reopen` (r:1 w:1)
    /// Proof: `PublicJobs::Reopen` (`max_values`: Some(1), `max_size`: Some(8194), added: 8689, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::ActiveJobs` (r:1 w:1)
    /// Proof: `PublicJobs::ActiveJobs` (`max_values`: Some(1), `max_size`: Some(65), added: 560, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Jobs` (r:1 w:1)
    /// Proof: `PublicJobs::Jobs` (`max_values`: None, `max_size`: Some(665), added: 3140, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Units` (r:256 w:256)
    /// Proof: `PublicJobs::Units` (`max_values`: None, `max_size`: Some(3613), added: 6088, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Seed` (r:0 w:1)
    /// Proof: `PublicJobs::Seed` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::CurrentRoster` (r:0 w:1)
    /// Proof: `PublicJobs::CurrentRoster` (`max_values`: Some(1), `max_size`: Some(289002), added: 289497, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Assigned` (r:0 w:768)
    /// Proof: `PublicJobs::Assigned` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::LastRound` (r:0 w:1)
    /// Proof: `PublicJobs::LastRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn start_round(w: u32, u: u32) -> Weight {
        Weight::from_parts(4_961_917_000, 9679)
            .saturating_add(Weight::from_parts(14_425_909, 0).saturating_mul(w.into()))
            .saturating_add(Weight::from_parts(54_991_091, 0).saturating_mul(u.into()))
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(w.into())))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(u.into())))
            .saturating_add(T::DbWeight::get().writes(6_u64))
            .saturating_add(T::DbWeight::get().writes((4_u64).saturating_mul(u.into())))
            .saturating_add(Weight::from_parts(0, 6086).saturating_mul(u.into()))
            .saturating_add(Weight::from_parts(0, 3276).saturating_mul(w.into()))
    }
    /// Storage: `PublicJobs::QueueBounds` (r:1 w:1)
    /// Proof: `PublicJobs::QueueBounds` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::SettledQueue` (r:64 w:64)
    /// Proof: `PublicJobs::SettledQueue` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
    /// Storage: `PublicJobs::Units` (r:64 w:64)
    /// Proof: `PublicJobs::Units` (`max_values`: None, `max_size`: Some(3613), added: 6088, mode: `MaxEncodedLen`)
    fn prune(n: u32) -> Weight {
        Weight::from_parts(15_234_000, 1501)
            .saturating_add(Weight::from_parts(10_894_208, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 6088).saturating_mul(n.into()))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn register() -> Weight {
        Weight::from_parts(30_231_000, 286790)
            .saturating_add(RocksDbWeight::get().reads(10_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn set_models() -> Weight {
        Weight::from_parts(29_592_000, 286790)
            .saturating_add(RocksDbWeight::get().reads(9_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn deregister() -> Weight {
        Weight::from_parts(24_764_000, 3773)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn ready() -> Weight {
        Weight::from_parts(15_020_000, 3773)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn publish() -> Weight {
        Weight::from_parts(28_293_000, 36715)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn cancel() -> Weight {
        Weight::from_parts(22_422_000, 4130)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn commit() -> Weight {
        Weight::from_parts(20_217_000, 7078)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn reveal() -> Weight {
        Weight::from_parts(119_068_000, 10818)
            .saturating_add(RocksDbWeight::get().reads(13_u64))
            .saturating_add(RocksDbWeight::get().writes(14_u64))
    }
    fn close() -> Weight {
        Weight::from_parts(123_609_000, 9339)
            .saturating_add(RocksDbWeight::get().reads(12_u64))
            .saturating_add(RocksDbWeight::get().writes(13_u64))
    }
    fn reveal_canary() -> Weight {
        Weight::from_parts(1_999_760_000, 81758)
            .saturating_add(RocksDbWeight::get().reads(53_u64))
            .saturating_add(RocksDbWeight::get().writes(20_u64))
    }
    fn claim(n: u32) -> Weight {
        Weight::from_parts(105_249_504, 6196)
            .saturating_add(Weight::from_parts(4_463_000, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(6_u64))
            .saturating_add(Weight::from_parts(0, 2524).saturating_mul(n.into()))
    }
    fn withdraw() -> Weight {
        Weight::from_parts(50_822_000, 4138)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn set_price_cap() -> Weight {
        Weight::from_parts(12_326_000, 1533)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn start_round(w: u32, u: u32) -> Weight {
        Weight::from_parts(4_961_917_000, 9679)
            .saturating_add(Weight::from_parts(14_425_909, 0).saturating_mul(w.into()))
            .saturating_add(Weight::from_parts(54_991_091, 0).saturating_mul(u.into()))
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(w.into())))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(u.into())))
            .saturating_add(RocksDbWeight::get().writes(6_u64))
            .saturating_add(RocksDbWeight::get().writes((4_u64).saturating_mul(u.into())))
            .saturating_add(Weight::from_parts(0, 6086).saturating_mul(u.into()))
            .saturating_add(Weight::from_parts(0, 3276).saturating_mul(w.into()))
    }
    fn prune(n: u32) -> Weight {
        Weight::from_parts(15_234_000, 1501)
            .saturating_add(Weight::from_parts(10_894_208, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
            .saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 6088).saturating_mul(n.into()))
    }
}
