//! Autogenerated weights for `pallet_pq_accounts`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-26.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_pq_accounts`.
pub trait WeightInfo {
    /// Benchmarked weight of `rotate_key`.
    fn rotate_key() -> Weight;
    /// Benchmarked weight of `authorize_ml_dsa_44`.
    fn authorize_ml_dsa_44() -> Weight;
    /// Benchmarked weight of `authorize_ml_dsa_65`.
    fn authorize_ml_dsa_65() -> Weight;
    /// Benchmarked weight of `authorize_ml_dsa_87`.
    fn authorize_ml_dsa_87() -> Weight;
    /// Benchmarked weight of `register_key`.
    fn register_key() -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `PqAccounts::Keys` (r:2 w:1)
    /// Proof: `PqAccounts::Keys` (`max_values`: None, `max_size`: Some(2629), added: 5104, mode: `MaxEncodedLen`)
    /// Storage: `PqAccounts::KeyOwner` (r:1 w:2)
    /// Proof: `PqAccounts::KeyOwner` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:0)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    fn rotate_key() -> Weight {
        Weight::from_parts(2_019_618_000, 11198)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `PqAccounts::Keys` (r:1 w:0)
    /// Proof: `PqAccounts::Keys` (`max_values`: None, `max_size`: Some(2629), added: 5104, mode: `MaxEncodedLen`)
    fn authorize_ml_dsa_44() -> Weight {
        Weight::from_parts(733_219_000, 6094).saturating_add(T::DbWeight::get().reads(1_u64))
    }
    /// Storage: `PqAccounts::Keys` (r:1 w:0)
    /// Proof: `PqAccounts::Keys` (`max_values`: None, `max_size`: Some(2629), added: 5104, mode: `MaxEncodedLen`)
    fn authorize_ml_dsa_65() -> Weight {
        Weight::from_parts(1_173_987_000, 6094).saturating_add(T::DbWeight::get().reads(1_u64))
    }
    /// Storage: `PqAccounts::Keys` (r:1 w:0)
    /// Proof: `PqAccounts::Keys` (`max_values`: None, `max_size`: Some(2629), added: 5104, mode: `MaxEncodedLen`)
    fn authorize_ml_dsa_87() -> Weight {
        Weight::from_parts(1_861_485_000, 6094).saturating_add(T::DbWeight::get().reads(1_u64))
    }
    /// Storage: `PqAccounts::RegisteredCount` (r:1 w:1)
    /// Proof: `PqAccounts::RegisteredCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `PqAccounts::KeyOwner` (r:0 w:1)
    /// Proof: `PqAccounts::KeyOwner` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
    /// Storage: `PqAccounts::Keys` (r:0 w:1)
    /// Proof: `PqAccounts::Keys` (`max_values`: None, `max_size`: Some(2629), added: 5104, mode: `MaxEncodedLen`)
    fn register_key() -> Weight {
        Weight::from_parts(81_489_000, 1493)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn rotate_key() -> Weight {
        Weight::from_parts(2_019_618_000, 11198)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn authorize_ml_dsa_44() -> Weight {
        Weight::from_parts(733_219_000, 6094).saturating_add(RocksDbWeight::get().reads(1_u64))
    }
    fn authorize_ml_dsa_65() -> Weight {
        Weight::from_parts(1_173_987_000, 6094).saturating_add(RocksDbWeight::get().reads(1_u64))
    }
    fn authorize_ml_dsa_87() -> Weight {
        Weight::from_parts(1_861_485_000, 6094).saturating_add(RocksDbWeight::get().reads(1_u64))
    }
    fn register_key() -> Weight {
        Weight::from_parts(81_489_000, 1493)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
}
