//! Byte-level vectors of the engine plugin protocol, shared with the plugin's Python tests
//! (`plugins/vllm/tests`). Regenerate with `AC_WRITE_VECTORS=1 cargo test -p ac-market-proto
//! --test engine_vectors`; the file must not change otherwise.

#![allow(clippy::unwrap_used, clippy::indexing_slicing)] // Test code.

use ac_market_proto::engine::{ENGINE_PROTOCOL_VERSION, EngineMode, EngineMsg, market_request_id};
use ac_toploc::{Bf16, Candidate, Phase};
use serde_json::{Value, json};

const PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/vectors/engine_protocol.json"
);

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn vector(name: &str, fields: Value, msg: &EngineMsg) -> Value {
    json!({"name": name, "message": fields, "frame": hex(&msg.to_frame().unwrap())})
}

fn vectors() -> Value {
    let id = format!("chatcmpl-{}-7a1b2c3d", "5a".repeat(32));
    let cands: Vec<(u32, u16)> = vec![(0, 0x3f80), (4095, 0xc2c8), (123_456, 0x0001)];
    let msgs = vec![
        vector(
            "hello",
            json!({"type": "hello", "version": ENGINE_PROTOCOL_VERSION, "hidden_size": 896, "mode": "prove"}),
            &EngineMsg::Hello {
                version: ENGINE_PROTOCOL_VERSION,
                hidden_size: 896,
                mode: EngineMode::Prove,
            },
        ),
        vector(
            "hello verify",
            json!({"type": "hello", "version": ENGINE_PROTOCOL_VERSION, "hidden_size": 3584, "mode": "verify"}),
            &EngineMsg::Hello {
                version: ENGINE_PROTOCOL_VERSION,
                hidden_size: 3584,
                mode: EngineMode::Verify,
            },
        ),
        vector(
            "welcome refusing the mode",
            json!({"type": "welcome", "version": ENGINE_PROTOCOL_VERSION, "topk": 0}),
            &EngineMsg::Welcome {
                version: ENGINE_PROTOCOL_VERSION,
                topk: 0,
            },
        ),
        vector(
            "welcome",
            json!({"type": "welcome", "version": ENGINE_PROTOCOL_VERSION, "topk": 128}),
            &EngineMsg::Welcome {
                version: ENGINE_PROTOCOL_VERSION,
                topk: 128,
            },
        ),
        vector(
            "prefill segment",
            json!({"type": "segment", "request": id, "phase": "prefill", "len": 7 * 896, "candidates": cands}),
            &EngineMsg::Segment {
                request: id.clone(),
                phase: Phase::Prefill,
                len: 7 * 896,
                candidates: cands
                    .iter()
                    .map(|(index, v)| Candidate {
                        index: *index,
                        value: Bf16(*v),
                    })
                    .collect(),
            },
        ),
        vector(
            "empty decode segment",
            json!({"type": "segment", "request": "r", "phase": "decode", "len": 0, "candidates": []}),
            &EngineMsg::Segment {
                request: "r".into(),
                phase: Phase::Decode,
                len: 0,
                candidates: vec![],
            },
        ),
        vector(
            "finish",
            json!({"type": "finish", "request": id}),
            &EngineMsg::Finish {
                request: id.clone(),
            },
        ),
    ];
    json!({
        "comment": "Frames of the AgentCoin engine plugin protocol (crates/ac-market-proto/src/engine.rs). Generated by tests/engine_vectors.rs.",
        "version": ENGINE_PROTOCOL_VERSION,
        "request_ids": [
            {"engine": id, "market": "5a".repeat(32)},
            {"engine": format!("cmpl-{}-0", "5a".repeat(32)), "market": "5a".repeat(32)},
            {"engine": "chatcmpl-0123-abcd", "market": null},
        ],
        "messages": msgs,
    })
}

#[test]
fn vectors_are_unchanged() {
    let expected = format!("{}\n", serde_json::to_string_pretty(&vectors()).unwrap());
    if std::env::var_os("AC_WRITE_VECTORS").is_some() {
        std::fs::write(PATH, &expected).unwrap();
    }
    assert_eq!(std::fs::read_to_string(PATH).unwrap(), expected);
}

#[test]
fn vectors_decode_and_ids_extract() {
    let v = vectors();
    for m in v["messages"].as_array().unwrap() {
        let frame = m["frame"].as_str().unwrap();
        let bytes: Vec<u8> = (0..frame.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&frame[i..i + 2], 16).unwrap())
            .collect();
        let msg = EngineMsg::decode(&bytes[4..]).unwrap();
        assert_eq!(hex(&msg.to_frame().unwrap()), frame);
    }
    for r in v["request_ids"].as_array().unwrap() {
        let got = market_request_id(r["engine"].as_str().unwrap()).map(|id| hex(&id));
        assert_eq!(got.as_deref(), r["market"].as_str());
    }
}
