//! Autogenerated weights for `pallet_credits`.
//!
//! Generated by `scripts/benchmark-pallet.sh` with frame-omni-bencher 60.0.0 on 2026-09-29.
//! Steps: `50`, repeat: `20`, hostname: `vm`, CPU: `Intel(R) Xeon(R) Processor @ 2.80GHz`.
//! Do not edit by hand: re-run the benchmarks instead.

#![allow(unused_parens, unused_imports, missing_docs, clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{Weight, constants::RocksDbWeight},
};

/// Weight functions of `pallet_credits`.
pub trait WeightInfo {
    /// Benchmarked weight of `deposit`.
    fn deposit() -> Weight;
    /// Benchmarked weight of `request_withdrawal`.
    fn request_withdrawal() -> Weight;
    /// Benchmarked weight of `withdraw`.
    fn withdraw() -> Weight;
    /// Benchmarked weight of `request_key_change`.
    fn request_key_change() -> Weight;
    /// Benchmarked weight of `redeem`.
    fn redeem() -> Weight;
}

/// Weights measured on the reference machine, with the runtime's database weights.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Gateways::Gateways` (r:1 w:0)
    /// Proof: `Gateways::Gateways` (`max_values`: None, `max_size`: Some(474), added: 2949, mode: `MaxEncodedLen`)
    /// Storage: `PqAccounts::Keys` (r:1 w:0)
    /// Proof: `PqAccounts::Keys` (`max_values`: None, `max_size`: Some(2629), added: 5104, mode: `MaxEncodedLen`)
    /// Storage: `Credits::Channels` (r:1 w:1)
    /// Proof: `Credits::Channels` (`max_values`: None, `max_size`: Some(190), added: 2665, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
    fn deposit() -> Weight {
        Weight::from_parts(96_958_000, 6094)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Credits::Channels` (r:1 w:1)
    /// Proof: `Credits::Channels` (`max_values`: None, `max_size`: Some(190), added: 2665, mode: `MaxEncodedLen`)
    /// Storage: `Credits::Params` (r:1 w:0)
    /// Proof: `Credits::Params` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn request_withdrawal() -> Weight {
        Weight::from_parts(20_731_000, 3655)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Credits::Channels` (r:1 w:1)
    /// Proof: `Credits::Channels` (`max_values`: None, `max_size`: Some(190), added: 2665, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
    fn withdraw() -> Weight {
        Weight::from_parts(59_738_000, 3694)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `PqAccounts::Keys` (r:1 w:0)
    /// Proof: `PqAccounts::Keys` (`max_values`: None, `max_size`: Some(2629), added: 5104, mode: `MaxEncodedLen`)
    /// Storage: `Credits::Channels` (r:1 w:1)
    /// Proof: `Credits::Channels` (`max_values`: None, `max_size`: Some(190), added: 2665, mode: `MaxEncodedLen`)
    /// Storage: `Credits::Params` (r:1 w:0)
    /// Proof: `Credits::Params` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn request_key_change() -> Weight {
        Weight::from_parts(45_060_000, 6094)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Credits::Channels` (r:1 w:1)
    /// Proof: `Credits::Channels` (`max_values`: None, `max_size`: Some(190), added: 2665, mode: `MaxEncodedLen`)
    /// Storage: `System::BlockHash` (r:1 w:0)
    /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `RefRate::Rate` (r:1 w:0)
    /// Proof: `RefRate::Rate` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
    fn redeem() -> Weight {
        Weight::from_parts(1_591_955_000, 3694)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
}

/// Same weights with RocksDB database weights, for tests and mocks.
impl WeightInfo for () {
    fn deposit() -> Weight {
        Weight::from_parts(96_958_000, 6094)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn request_withdrawal() -> Weight {
        Weight::from_parts(20_731_000, 3655)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn withdraw() -> Weight {
        Weight::from_parts(59_738_000, 3694)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn request_key_change() -> Weight {
        Weight::from_parts(45_060_000, 6094)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn redeem() -> Weight {
        Weight::from_parts(1_591_955_000, 3694)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
}
